// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: api/qm/deployment/v1/deployment.proto

package deploymentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DeploymentLayerService_Get_FullMethodName           = "/qm.deployment.v1.DeploymentLayerService/Get"
	DeploymentLayerService_PutIfAbsent_FullMethodName   = "/qm.deployment.v1.DeploymentLayerService/PutIfAbsent"
	DeploymentLayerService_CompareAndSet_FullMethodName = "/qm.deployment.v1.DeploymentLayerService/CompareAndSet"
)

// DeploymentLayerServiceClient is the client API for DeploymentLayerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeploymentLayerServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
	PutIfAbsent(ctx context.Context, in *PutIfAbsentRequest, opts ...grpc.CallOption) (*PutIfAbsentReply, error)
	CompareAndSet(ctx context.Context, in *CompareAndSetRequest, opts ...grpc.CallOption) (*CompareAndSetReply, error)
}

type deploymentLayerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeploymentLayerServiceClient(cc grpc.ClientConnInterface) DeploymentLayerServiceClient {
	return &deploymentLayerServiceClient{cc}
}

func (c *deploymentLayerServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, DeploymentLayerService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentLayerServiceClient) PutIfAbsent(ctx context.Context, in *PutIfAbsentRequest, opts ...grpc.CallOption) (*PutIfAbsentReply, error) {
	out := new(PutIfAbsentReply)
	err := c.cc.Invoke(ctx, DeploymentLayerService_PutIfAbsent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentLayerServiceClient) CompareAndSet(ctx context.Context, in *CompareAndSetRequest, opts ...grpc.CallOption) (*CompareAndSetReply, error) {
	out := new(CompareAndSetReply)
	err := c.cc.Invoke(ctx, DeploymentLayerService_CompareAndSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeploymentLayerServiceServer is the server API for DeploymentLayerService service.
// All implementations must embed UnimplementedDeploymentLayerServiceServer
// for forward compatibility
type DeploymentLayerServiceServer interface {
	Get(context.Context, *GetRequest) (*GetReply, error)
	PutIfAbsent(context.Context, *PutIfAbsentRequest) (*PutIfAbsentReply, error)
	CompareAndSet(context.Context, *CompareAndSetRequest) (*CompareAndSetReply, error)
	mustEmbedUnimplementedDeploymentLayerServiceServer()
}

// UnimplementedDeploymentLayerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDeploymentLayerServiceServer struct {
}

func (UnimplementedDeploymentLayerServiceServer) Get(context.Context, *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDeploymentLayerServiceServer) PutIfAbsent(context.Context, *PutIfAbsentRequest) (*PutIfAbsentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutIfAbsent not implemented")
}
func (UnimplementedDeploymentLayerServiceServer) CompareAndSet(context.Context, *CompareAndSetRequest) (*CompareAndSetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompareAndSet not implemented")
}
func (UnimplementedDeploymentLayerServiceServer) mustEmbedUnimplementedDeploymentLayerServiceServer() {
}

// UnsafeDeploymentLayerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeploymentLayerServiceServer will
// result in compilation errors.
type UnsafeDeploymentLayerServiceServer interface {
	mustEmbedUnimplementedDeploymentLayerServiceServer()
}

func RegisterDeploymentLayerServiceServer(s grpc.ServiceRegistrar, srv DeploymentLayerServiceServer) {
	s.RegisterService(&DeploymentLayerService_ServiceDesc, srv)
}

func _DeploymentLayerService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentLayerServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentLayerService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentLayerServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeploymentLayerService_PutIfAbsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutIfAbsentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentLayerServiceServer).PutIfAbsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentLayerService_PutIfAbsent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentLayerServiceServer).PutIfAbsent(ctx, req.(*PutIfAbsentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeploymentLayerService_CompareAndSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareAndSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentLayerServiceServer).CompareAndSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentLayerService_CompareAndSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentLayerServiceServer).CompareAndSet(ctx, req.(*CompareAndSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeploymentLayerService_ServiceDesc is the grpc.ServiceDesc for DeploymentLayerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeploymentLayerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qm.deployment.v1.DeploymentLayerService",
	HandlerType: (*DeploymentLayerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _DeploymentLayerService_Get_Handler,
		},
		{
			MethodName: "PutIfAbsent",
			Handler:    _DeploymentLayerService_PutIfAbsent_Handler,
		},
		{
			MethodName: "CompareAndSet",
			Handler:    _DeploymentLayerService_CompareAndSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/qm/deployment/v1/deployment.proto",
}
