// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v7.35.1
// source: api/qm/cron/v1/cron.proto

package cronv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cron struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload          []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	NextFireAtUnixMs int64  `protobuf:"varint,3,opt,name=next_fire_at_unix_ms,json=nextFireAtUnixMs,proto3" json:"next_fire_at_unix_ms,omitempty"`
}

func (x *Cron) Reset() {
	*x = Cron{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cron) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cron) ProtoMessage() {}

func (x *Cron) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cron.ProtoReflect.Descriptor instead.
func (*Cron) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{0}
}

func (x *Cron) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cron) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Cron) GetNextFireAtUnixMs() int64 {
	if x != nil {
		return x.NextFireAtUnixMs
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool  `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Cron  *Cron `protobuf:"bytes,2,opt,name=cron,proto3" json:"cron,omitempty"`
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{2}
}

func (x *GetReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetReply) GetCron() *Cron {
	if x != nil {
		return x.Cron
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{3}
}

type ListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Crons []*Cron `protobuf:"bytes,1,rep,name=crons,proto3" json:"crons,omitempty"`
}

func (x *ListReply) Reset() {
	*x = ListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReply) ProtoMessage() {}

func (x *ListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReply.ProtoReflect.Descriptor instead.
func (*ListReply) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{4}
}

func (x *ListReply) GetCrons() []*Cron {
	if x != nil {
		return x.Crons
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{5}
}

func (x *PutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PutRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PutIfAbsentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *PutIfAbsentRequest) Reset() {
	*x = PutIfAbsentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutIfAbsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutIfAbsentRequest) ProtoMessage() {}

func (x *PutIfAbsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutIfAbsentRequest.ProtoReflect.Descriptor instead.
func (*PutIfAbsentRequest) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{6}
}

func (x *PutIfAbsentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PutIfAbsentRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PutReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cron *Cron `protobuf:"bytes,1,opt,name=cron,proto3" json:"cron,omitempty"`
}

func (x *PutReply) Reset() {
	*x = PutReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutReply) ProtoMessage() {}

func (x *PutReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutReply.ProtoReflect.Descriptor instead.
func (*PutReply) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{7}
}

func (x *PutReply) GetCron() *Cron {
	if x != nil {
		return x.Cron
	}
	return nil
}

type MergeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Patch      []byte   `protobuf:"bytes,2,opt,name=patch,proto3" json:"patch,omitempty"`
	RemoveKeys []string `protobuf:"bytes,3,rep,name=remove_keys,json=removeKeys,proto3" json:"remove_keys,omitempty"`
}

func (x *MergeRequest) Reset() {
	*x = MergeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRequest) ProtoMessage() {}

func (x *MergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRequest.ProtoReflect.Descriptor instead.
func (*MergeRequest) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{8}
}

func (x *MergeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MergeRequest) GetPatch() []byte {
	if x != nil {
		return x.Patch
	}
	return nil
}

func (x *MergeRequest) GetRemoveKeys() []string {
	if x != nil {
		return x.RemoveKeys
	}
	return nil
}

type MergeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool  `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Cron  *Cron `protobuf:"bytes,2,opt,name=cron,proto3" json:"cron,omitempty"`
}

func (x *MergeReply) Reset() {
	*x = MergeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeReply) ProtoMessage() {}

func (x *MergeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeReply.ProtoReflect.Descriptor instead.
func (*MergeReply) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{9}
}

func (x *MergeReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *MergeReply) GetCron() *Cron {
	if x != nil {
		return x.Cron
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteReply) Reset() {
	*x = DeleteReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReply) ProtoMessage() {}

func (x *DeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReply.ProtoReflect.Descriptor instead.
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{11}
}

type TakeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TakeRequest) Reset() {
	*x = TakeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeRequest) ProtoMessage() {}

func (x *TakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeRequest.ProtoReflect.Descriptor instead.
func (*TakeRequest) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{12}
}

func (x *TakeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TakeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool  `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Cron  *Cron `protobuf:"bytes,2,opt,name=cron,proto3" json:"cron,omitempty"`
}

func (x *TakeReply) Reset() {
	*x = TakeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TakeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeReply) ProtoMessage() {}

func (x *TakeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeReply.ProtoReflect.Descriptor instead.
func (*TakeReply) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{13}
}

func (x *TakeReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *TakeReply) GetCron() *Cron {
	if x != nil {
		return x.Cron
	}
	return nil
}

type ListDueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NowUnixMs int64 `protobuf:"varint,1,opt,name=now_unix_ms,json=nowUnixMs,proto3" json:"now_unix_ms,omitempty"`
	Limit     int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListDueRequest) Reset() {
	*x = ListDueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDueRequest) ProtoMessage() {}

func (x *ListDueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDueRequest.ProtoReflect.Descriptor instead.
func (*ListDueRequest) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{14}
}

func (x *ListDueRequest) GetNowUnixMs() int64 {
	if x != nil {
		return x.NowUnixMs
	}
	return 0
}

func (x *ListDueRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Crons []*Cron `protobuf:"bytes,1,rep,name=crons,proto3" json:"crons,omitempty"`
}

func (x *ListDueReply) Reset() {
	*x = ListDueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDueReply) ProtoMessage() {}

func (x *ListDueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDueReply.ProtoReflect.Descriptor instead.
func (*ListDueReply) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{15}
}

func (x *ListDueReply) GetCrons() []*Cron {
	if x != nil {
		return x.Crons
	}
	return nil
}

type ClaimSlotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ScheduledAtUnixMs int64  `protobuf:"varint,2,opt,name=scheduled_at_unix_ms,json=scheduledAtUnixMs,proto3" json:"scheduled_at_unix_ms,omitempty"`
	FiredAtUnixMs     int64  `protobuf:"varint,3,opt,name=fired_at_unix_ms,json=firedAtUnixMs,proto3" json:"fired_at_unix_ms,omitempty"`
	NextFireAtUnixMs  int64  `protobuf:"varint,4,opt,name=next_fire_at_unix_ms,json=nextFireAtUnixMs,proto3" json:"next_fire_at_unix_ms,omitempty"`
	HasNextFireAt     bool   `protobuf:"varint,5,opt,name=has_next_fire_at,json=hasNextFireAt,proto3" json:"has_next_fire_at,omitempty"`
}

func (x *ClaimSlotRequest) Reset() {
	*x = ClaimSlotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimSlotRequest) ProtoMessage() {}

func (x *ClaimSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimSlotRequest.ProtoReflect.Descriptor instead.
func (*ClaimSlotRequest) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{16}
}

func (x *ClaimSlotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClaimSlotRequest) GetScheduledAtUnixMs() int64 {
	if x != nil {
		return x.ScheduledAtUnixMs
	}
	return 0
}

func (x *ClaimSlotRequest) GetFiredAtUnixMs() int64 {
	if x != nil {
		return x.FiredAtUnixMs
	}
	return 0
}

func (x *ClaimSlotRequest) GetNextFireAtUnixMs() int64 {
	if x != nil {
		return x.NextFireAtUnixMs
	}
	return 0
}

func (x *ClaimSlotRequest) GetHasNextFireAt() bool {
	if x != nil {
		return x.HasNextFireAt
	}
	return false
}

type ClaimSlotReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Claimed bool `protobuf:"varint,1,opt,name=claimed,proto3" json:"claimed,omitempty"`
}

func (x *ClaimSlotReply) Reset() {
	*x = ClaimSlotReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimSlotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimSlotReply) ProtoMessage() {}

func (x *ClaimSlotReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimSlotReply.ProtoReflect.Descriptor instead.
func (*ClaimSlotReply) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{17}
}

func (x *ClaimSlotReply) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

type UnclaimSlotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ScheduledAtUnixMs      int64  `protobuf:"varint,2,opt,name=scheduled_at_unix_ms,json=scheduledAtUnixMs,proto3" json:"scheduled_at_unix_ms,omitempty"`
	FiredAtUnixMs          int64  `protobuf:"varint,3,opt,name=fired_at_unix_ms,json=firedAtUnixMs,proto3" json:"fired_at_unix_ms,omitempty"`
	PriorLastFiredAtUnixMs int64  `protobuf:"varint,4,opt,name=prior_last_fired_at_unix_ms,json=priorLastFiredAtUnixMs,proto3" json:"prior_last_fired_at_unix_ms,omitempty"`
	HasPriorLastFiredAt    bool   `protobuf:"varint,5,opt,name=has_prior_last_fired_at,json=hasPriorLastFiredAt,proto3" json:"has_prior_last_fired_at,omitempty"`
}

func (x *UnclaimSlotRequest) Reset() {
	*x = UnclaimSlotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnclaimSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnclaimSlotRequest) ProtoMessage() {}

func (x *UnclaimSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnclaimSlotRequest.ProtoReflect.Descriptor instead.
func (*UnclaimSlotRequest) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{18}
}

func (x *UnclaimSlotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UnclaimSlotRequest) GetScheduledAtUnixMs() int64 {
	if x != nil {
		return x.ScheduledAtUnixMs
	}
	return 0
}

func (x *UnclaimSlotRequest) GetFiredAtUnixMs() int64 {
	if x != nil {
		return x.FiredAtUnixMs
	}
	return 0
}

func (x *UnclaimSlotRequest) GetPriorLastFiredAtUnixMs() int64 {
	if x != nil {
		return x.PriorLastFiredAtUnixMs
	}
	return 0
}

func (x *UnclaimSlotRequest) GetHasPriorLastFiredAt() bool {
	if x != nil {
		return x.HasPriorLastFiredAt
	}
	return false
}

type UnclaimSlotReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Restored bool `protobuf:"varint,1,opt,name=restored,proto3" json:"restored,omitempty"`
}

func (x *UnclaimSlotReply) Reset() {
	*x = UnclaimSlotReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnclaimSlotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnclaimSlotReply) ProtoMessage() {}

func (x *UnclaimSlotReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnclaimSlotReply.ProtoReflect.Descriptor instead.
func (*UnclaimSlotReply) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{19}
}

func (x *UnclaimSlotReply) GetRestored() bool {
	if x != nil {
		return x.Restored
	}
	return false
}

type RecordFireRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Entry []byte `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *RecordFireRequest) Reset() {
	*x = RecordFireRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordFireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFireRequest) ProtoMessage() {}

func (x *RecordFireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFireRequest.ProtoReflect.Descriptor instead.
func (*RecordFireRequest) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{20}
}

func (x *RecordFireRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecordFireRequest) GetEntry() []byte {
	if x != nil {
		return x.Entry
	}
	return nil
}

type RecordFireReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updated bool `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *RecordFireReply) Reset() {
	*x = RecordFireReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordFireReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFireReply) ProtoMessage() {}

func (x *RecordFireReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFireReply.ProtoReflect.Descriptor instead.
func (*RecordFireReply) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{21}
}

func (x *RecordFireReply) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type MarkFiredRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FiredAtUnixMs    int64  `protobuf:"varint,2,opt,name=fired_at_unix_ms,json=firedAtUnixMs,proto3" json:"fired_at_unix_ms,omitempty"`
	NextFireAtUnixMs int64  `protobuf:"varint,3,opt,name=next_fire_at_unix_ms,json=nextFireAtUnixMs,proto3" json:"next_fire_at_unix_ms,omitempty"`
	HasNextFireAt    bool   `protobuf:"varint,4,opt,name=has_next_fire_at,json=hasNextFireAt,proto3" json:"has_next_fire_at,omitempty"`
}

func (x *MarkFiredRequest) Reset() {
	*x = MarkFiredRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkFiredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkFiredRequest) ProtoMessage() {}

func (x *MarkFiredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkFiredRequest.ProtoReflect.Descriptor instead.
func (*MarkFiredRequest) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{22}
}

func (x *MarkFiredRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MarkFiredRequest) GetFiredAtUnixMs() int64 {
	if x != nil {
		return x.FiredAtUnixMs
	}
	return 0
}

func (x *MarkFiredRequest) GetNextFireAtUnixMs() int64 {
	if x != nil {
		return x.NextFireAtUnixMs
	}
	return 0
}

func (x *MarkFiredRequest) GetHasNextFireAt() bool {
	if x != nil {
		return x.HasNextFireAt
	}
	return false
}

type MarkFiredReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updated bool `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *MarkFiredReply) Reset() {
	*x = MarkFiredReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_cron_v1_cron_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkFiredReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkFiredReply) ProtoMessage() {}

func (x *MarkFiredReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_cron_v1_cron_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkFiredReply.ProtoReflect.Descriptor instead.
func (*MarkFiredReply) Descriptor() ([]byte, []int) {
	return file_api_qm_cron_v1_cron_proto_rawDescGZIP(), []int{23}
}

func (x *MarkFiredReply) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

var File_api_qm_cron_v1_cron_proto protoreflect.FileDescriptor

var file_api_qm_cron_v1_cron_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x71, 0x6d, 0x2f, 0x63, 0x72, 0x6f, 0x6e, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x71, 0x6d, 0x2e,
	0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x60, 0x0a, 0x04, 0x43, 0x72, 0x6f, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2e, 0x0a, 0x14, 0x6e, 0x65, 0x78,
	0x74, 0x5f, 0x66, 0x69, 0x72, 0x65, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6e, 0x65, 0x78, 0x74, 0x46, 0x69, 0x72,
	0x65, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73, 0x22, 0x1c, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x63, 0x72, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x6f, 0x6e, 0x52, 0x04, 0x63, 0x72, 0x6f, 0x6e, 0x22,
	0x0d, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x33,
	0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x63,
	0x72, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x71, 0x6d, 0x2e,
	0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x6f, 0x6e, 0x52, 0x05, 0x63, 0x72,
	0x6f, 0x6e, 0x73, 0x22, 0x36, 0x0a, 0x0a, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x3e, 0x0a, 0x12, 0x50,
	0x75, 0x74, 0x49, 0x66, 0x41, 0x62, 0x73, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x30, 0x0a, 0x08, 0x50,
	0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x24, 0x0a, 0x04, 0x63, 0x72, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x6f, 0x6e, 0x52, 0x04, 0x63, 0x72, 0x6f, 0x6e, 0x22, 0x55, 0x0a,
	0x0c, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x6b, 0x65,
	0x79, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x4b, 0x65, 0x79, 0x73, 0x22, 0x48, 0x0a, 0x0a, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x63, 0x72, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x6f, 0x6e, 0x52, 0x04, 0x63, 0x72, 0x6f, 0x6e, 0x22, 0x1f,
	0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x0d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d,
	0x0a, 0x0b, 0x54, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x47, 0x0a,
	0x09, 0x54, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f,
	0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x12, 0x24, 0x0a, 0x04, 0x63, 0x72, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x6f, 0x6e,
	0x52, 0x04, 0x63, 0x72, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x75,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0b, 0x6e, 0x6f, 0x77, 0x5f,
	0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e,
	0x6f, 0x77, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x36,
	0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x26,
	0x0a, 0x05, 0x63, 0x72, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x6f, 0x6e, 0x52,
	0x05, 0x63, 0x72, 0x6f, 0x6e, 0x73, 0x22, 0xd5, 0x01, 0x0a, 0x10, 0x43, 0x6c, 0x61, 0x69, 0x6d,
	0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x14, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78,
	0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x73, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x64, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73, 0x12, 0x27, 0x0a, 0x10,
	0x66, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x66, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74, 0x55,
	0x6e, 0x69, 0x78, 0x4d, 0x73, 0x12, 0x2e, 0x0a, 0x14, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x66, 0x69,
	0x72, 0x65, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x10, 0x6e, 0x65, 0x78, 0x74, 0x46, 0x69, 0x72, 0x65, 0x41, 0x74, 0x55,
	0x6e, 0x69, 0x78, 0x4d, 0x73, 0x12, 0x27, 0x0a, 0x10, 0x68, 0x61, 0x73, 0x5f, 0x6e, 0x65, 0x78,
	0x74, 0x5f, 0x66, 0x69, 0x72, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0d, 0x68, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x46, 0x69, 0x72, 0x65, 0x41, 0x74, 0x22, 0x2a,
	0x0a, 0x0e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x22, 0xf1, 0x01, 0x0a, 0x12, 0x55,
	0x6e, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x2f, 0x0a, 0x14, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x11, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78,
	0x4d, 0x73, 0x12, 0x27, 0x0a, 0x10, 0x66, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x75,
	0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x66, 0x69,
	0x72, 0x65, 0x64, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73, 0x12, 0x3b, 0x0a, 0x1b, 0x70,
	0x72, 0x69, 0x6f, 0x72, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x66, 0x69, 0x72, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x16, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x46, 0x69, 0x72, 0x65, 0x64,
	0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73, 0x12, 0x34, 0x0a, 0x17, 0x68, 0x61, 0x73, 0x5f,
	0x70, 0x72, 0x69, 0x6f, 0x72, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x66, 0x69, 0x72, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x68, 0x61, 0x73, 0x50, 0x72,
	0x69, 0x6f, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x46, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2e,
	0x0a, 0x10, 0x55, 0x6e, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x22, 0x39,
	0x0a, 0x11, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x46, 0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x2b, 0x0a, 0x0f, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x46, 0x69, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0xa4, 0x01, 0x0a, 0x10, 0x4d, 0x61, 0x72, 0x6b, 0x46,
	0x69, 0x72, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x10, 0x66,
	0x69, 0x72, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x66, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74, 0x55, 0x6e,
	0x69, 0x78, 0x4d, 0x73, 0x12, 0x2e, 0x0a, 0x14, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x66, 0x69, 0x72,
	0x65, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x10, 0x6e, 0x65, 0x78, 0x74, 0x46, 0x69, 0x72, 0x65, 0x41, 0x74, 0x55, 0x6e,
	0x69, 0x78, 0x4d, 0x73, 0x12, 0x27, 0x0a, 0x10, 0x68, 0x61, 0x73, 0x5f, 0x6e, 0x65, 0x78, 0x74,
	0x5f, 0x66, 0x69, 0x72, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d,
	0x68, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x46, 0x69, 0x72, 0x65, 0x41, 0x74, 0x22, 0x2a, 0x0a,
	0x0e, 0x4d, 0x61, 0x72, 0x6b, 0x46, 0x69, 0x72, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x32, 0x8b, 0x06, 0x0a, 0x0b, 0x43, 0x72,
	0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x03, 0x47, 0x65, 0x74,
	0x12, 0x16, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x36,
	0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x33, 0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x16, 0x2e,
	0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x43, 0x0a, 0x0b, 0x50,
	0x75, 0x74, 0x49, 0x66, 0x41, 0x62, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x2e, 0x71, 0x6d, 0x2e,
	0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x49, 0x66, 0x41, 0x62, 0x73,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x71, 0x6d, 0x2e,
	0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x39, 0x0a, 0x05, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x12, 0x18, 0x2e, 0x71, 0x6d, 0x2e, 0x63,
	0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3c, 0x0a, 0x06, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x36, 0x0a, 0x04, 0x54, 0x61, 0x6b,
	0x65, 0x12, 0x17, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x61, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x71, 0x6d, 0x2e,
	0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x3f, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x75, 0x65, 0x12, 0x1a, 0x2e, 0x71,
	0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x75,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x75, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x45, 0x0a, 0x09, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x12,
	0x1c, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x61,
	0x69, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d,
	0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4b, 0x0a, 0x0b, 0x55, 0x6e, 0x63,
	0x6c, 0x61, 0x69, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x1e, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x53, 0x6c, 0x6f,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x53, 0x6c, 0x6f,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x46, 0x69, 0x72, 0x65, 0x12, 0x1d, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x46, 0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x46, 0x69, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x45, 0x0a, 0x09, 0x4d, 0x61, 0x72, 0x6b, 0x46, 0x69, 0x72, 0x65, 0x64, 0x12, 0x1c, 0x2e,
	0x71, 0x6d, 0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x46,
	0x69, 0x72, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x71, 0x6d,
	0x2e, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x46, 0x69, 0x72,
	0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x65, 0x6a, 0x77, 0x2f, 0x71, 0x6d, 0x2d, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x71, 0x6d, 0x2f, 0x63, 0x72, 0x6f,
	0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x72, 0x6f, 0x6e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_qm_cron_v1_cron_proto_rawDescOnce sync.Once
	file_api_qm_cron_v1_cron_proto_rawDescData = file_api_qm_cron_v1_cron_proto_rawDesc
)

func file_api_qm_cron_v1_cron_proto_rawDescGZIP() []byte {
	file_api_qm_cron_v1_cron_proto_rawDescOnce.Do(func() {
		file_api_qm_cron_v1_cron_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_qm_cron_v1_cron_proto_rawDescData)
	})
	return file_api_qm_cron_v1_cron_proto_rawDescData
}

var file_api_qm_cron_v1_cron_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_qm_cron_v1_cron_proto_goTypes = []interface{}{
	(*Cron)(nil),               // 0: qm.cron.v1.Cron
	(*GetRequest)(nil),         // 1: qm.cron.v1.GetRequest
	(*GetReply)(nil),           // 2: qm.cron.v1.GetReply
	(*ListRequest)(nil),        // 3: qm.cron.v1.ListRequest
	(*ListReply)(nil),          // 4: qm.cron.v1.ListReply
	(*PutRequest)(nil),         // 5: qm.cron.v1.PutRequest
	(*PutIfAbsentRequest)(nil), // 6: qm.cron.v1.PutIfAbsentRequest
	(*PutReply)(nil),           // 7: qm.cron.v1.PutReply
	(*MergeRequest)(nil),       // 8: qm.cron.v1.MergeRequest
	(*MergeReply)(nil),         // 9: qm.cron.v1.MergeReply
	(*DeleteRequest)(nil),      // 10: qm.cron.v1.DeleteRequest
	(*DeleteReply)(nil),        // 11: qm.cron.v1.DeleteReply
	(*TakeRequest)(nil),        // 12: qm.cron.v1.TakeRequest
	(*TakeReply)(nil),          // 13: qm.cron.v1.TakeReply
	(*ListDueRequest)(nil),     // 14: qm.cron.v1.ListDueRequest
	(*ListDueReply)(nil),       // 15: qm.cron.v1.ListDueReply
	(*ClaimSlotRequest)(nil),   // 16: qm.cron.v1.ClaimSlotRequest
	(*ClaimSlotReply)(nil),     // 17: qm.cron.v1.ClaimSlotReply
	(*UnclaimSlotRequest)(nil), // 18: qm.cron.v1.UnclaimSlotRequest
	(*UnclaimSlotReply)(nil),   // 19: qm.cron.v1.UnclaimSlotReply
	(*RecordFireRequest)(nil),  // 20: qm.cron.v1.RecordFireRequest
	(*RecordFireReply)(nil),    // 21: qm.cron.v1.RecordFireReply
	(*MarkFiredRequest)(nil),   // 22: qm.cron.v1.MarkFiredRequest
	(*MarkFiredReply)(nil),     // 23: qm.cron.v1.MarkFiredReply
}
var file_api_qm_cron_v1_cron_proto_depIdxs = []int32{
	0,  // 0: qm.cron.v1.GetReply.cron:type_name -> qm.cron.v1.Cron
	0,  // 1: qm.cron.v1.ListReply.crons:type_name -> qm.cron.v1.Cron
	0,  // 2: qm.cron.v1.PutReply.cron:type_name -> qm.cron.v1.Cron
	0,  // 3: qm.cron.v1.MergeReply.cron:type_name -> qm.cron.v1.Cron
	0,  // 4: qm.cron.v1.TakeReply.cron:type_name -> qm.cron.v1.Cron
	0,  // 5: qm.cron.v1.ListDueReply.crons:type_name -> qm.cron.v1.Cron
	1,  // 6: qm.cron.v1.CronService.Get:input_type -> qm.cron.v1.GetRequest
	3,  // 7: qm.cron.v1.CronService.List:input_type -> qm.cron.v1.ListRequest
	5,  // 8: qm.cron.v1.CronService.Put:input_type -> qm.cron.v1.PutRequest
	6,  // 9: qm.cron.v1.CronService.PutIfAbsent:input_type -> qm.cron.v1.PutIfAbsentRequest
	8,  // 10: qm.cron.v1.CronService.Merge:input_type -> qm.cron.v1.MergeRequest
	10, // 11: qm.cron.v1.CronService.Delete:input_type -> qm.cron.v1.DeleteRequest
	12, // 12: qm.cron.v1.CronService.Take:input_type -> qm.cron.v1.TakeRequest
	14, // 13: qm.cron.v1.CronService.ListDue:input_type -> qm.cron.v1.ListDueRequest
	16, // 14: qm.cron.v1.CronService.ClaimSlot:input_type -> qm.cron.v1.ClaimSlotRequest
	18, // 15: qm.cron.v1.CronService.UnclaimSlot:input_type -> qm.cron.v1.UnclaimSlotRequest
	20, // 16: qm.cron.v1.CronService.RecordFire:input_type -> qm.cron.v1.RecordFireRequest
	22, // 17: qm.cron.v1.CronService.MarkFired:input_type -> qm.cron.v1.MarkFiredRequest
	2,  // 18: qm.cron.v1.CronService.Get:output_type -> qm.cron.v1.GetReply
	4,  // 19: qm.cron.v1.CronService.List:output_type -> qm.cron.v1.ListReply
	7,  // 20: qm.cron.v1.CronService.Put:output_type -> qm.cron.v1.PutReply
	7,  // 21: qm.cron.v1.CronService.PutIfAbsent:output_type -> qm.cron.v1.PutReply
	9,  // 22: qm.cron.v1.CronService.Merge:output_type -> qm.cron.v1.MergeReply
	11, // 23: qm.cron.v1.CronService.Delete:output_type -> qm.cron.v1.DeleteReply
	13, // 24: qm.cron.v1.CronService.Take:output_type -> qm.cron.v1.TakeReply
	15, // 25: qm.cron.v1.CronService.ListDue:output_type -> qm.cron.v1.ListDueReply
	17, // 26: qm.cron.v1.CronService.ClaimSlot:output_type -> qm.cron.v1.ClaimSlotReply
	19, // 27: qm.cron.v1.CronService.UnclaimSlot:output_type -> qm.cron.v1.UnclaimSlotReply
	21, // 28: qm.cron.v1.CronService.RecordFire:output_type -> qm.cron.v1.RecordFireReply
	23, // 29: qm.cron.v1.CronService.MarkFired:output_type -> qm.cron.v1.MarkFiredReply
	18, // [18:30] is the sub-list for method output_type
	6,  // [6:18] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_qm_cron_v1_cron_proto_init() }
func file_api_qm_cron_v1_cron_proto_init() {
	if File_api_qm_cron_v1_cron_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_qm_cron_v1_cron_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cron); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutIfAbsentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TakeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TakeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimSlotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimSlotReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnclaimSlotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnclaimSlotReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordFireRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordFireReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkFiredRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_cron_v1_cron_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkFiredReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_qm_cron_v1_cron_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_qm_cron_v1_cron_proto_goTypes,
		DependencyIndexes: file_api_qm_cron_v1_cron_proto_depIdxs,
		MessageInfos:      file_api_qm_cron_v1_cron_proto_msgTypes,
	}.Build()
	File_api_qm_cron_v1_cron_proto = out.File
	file_api_qm_cron_v1_cron_proto_rawDesc = nil
	file_api_qm_cron_v1_cron_proto_goTypes = nil
	file_api_qm_cron_v1_cron_proto_depIdxs = nil
}
