// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: api/qm/cron/v1/cron.proto

package cronv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CronService_Get_FullMethodName         = "/qm.cron.v1.CronService/Get"
	CronService_List_FullMethodName        = "/qm.cron.v1.CronService/List"
	CronService_Put_FullMethodName         = "/qm.cron.v1.CronService/Put"
	CronService_PutIfAbsent_FullMethodName = "/qm.cron.v1.CronService/PutIfAbsent"
	CronService_Merge_FullMethodName       = "/qm.cron.v1.CronService/Merge"
	CronService_Delete_FullMethodName      = "/qm.cron.v1.CronService/Delete"
	CronService_Take_FullMethodName        = "/qm.cron.v1.CronService/Take"
	CronService_ListDue_FullMethodName     = "/qm.cron.v1.CronService/ListDue"
	CronService_ClaimSlot_FullMethodName   = "/qm.cron.v1.CronService/ClaimSlot"
	CronService_UnclaimSlot_FullMethodName = "/qm.cron.v1.CronService/UnclaimSlot"
	CronService_RecordFire_FullMethodName  = "/qm.cron.v1.CronService/RecordFire"
	CronService_MarkFired_FullMethodName   = "/qm.cron.v1.CronService/MarkFired"
)

// CronServiceClient is the client API for CronService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CronServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutReply, error)
	PutIfAbsent(ctx context.Context, in *PutIfAbsentRequest, opts ...grpc.CallOption) (*PutReply, error)
	Merge(ctx context.Context, in *MergeRequest, opts ...grpc.CallOption) (*MergeReply, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error)
	Take(ctx context.Context, in *TakeRequest, opts ...grpc.CallOption) (*TakeReply, error)
	ListDue(ctx context.Context, in *ListDueRequest, opts ...grpc.CallOption) (*ListDueReply, error)
	ClaimSlot(ctx context.Context, in *ClaimSlotRequest, opts ...grpc.CallOption) (*ClaimSlotReply, error)
	UnclaimSlot(ctx context.Context, in *UnclaimSlotRequest, opts ...grpc.CallOption) (*UnclaimSlotReply, error)
	RecordFire(ctx context.Context, in *RecordFireRequest, opts ...grpc.CallOption) (*RecordFireReply, error)
	MarkFired(ctx context.Context, in *MarkFiredRequest, opts ...grpc.CallOption) (*MarkFiredReply, error)
}

type cronServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCronServiceClient(cc grpc.ClientConnInterface) CronServiceClient {
	return &cronServiceClient{cc}
}

func (c *cronServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, CronService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := c.cc.Invoke(ctx, CronService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutReply, error) {
	out := new(PutReply)
	err := c.cc.Invoke(ctx, CronService_Put_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) PutIfAbsent(ctx context.Context, in *PutIfAbsentRequest, opts ...grpc.CallOption) (*PutReply, error) {
	out := new(PutReply)
	err := c.cc.Invoke(ctx, CronService_PutIfAbsent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) Merge(ctx context.Context, in *MergeRequest, opts ...grpc.CallOption) (*MergeReply, error) {
	out := new(MergeReply)
	err := c.cc.Invoke(ctx, CronService_Merge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error) {
	out := new(DeleteReply)
	err := c.cc.Invoke(ctx, CronService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) Take(ctx context.Context, in *TakeRequest, opts ...grpc.CallOption) (*TakeReply, error) {
	out := new(TakeReply)
	err := c.cc.Invoke(ctx, CronService_Take_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) ListDue(ctx context.Context, in *ListDueRequest, opts ...grpc.CallOption) (*ListDueReply, error) {
	out := new(ListDueReply)
	err := c.cc.Invoke(ctx, CronService_ListDue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) ClaimSlot(ctx context.Context, in *ClaimSlotRequest, opts ...grpc.CallOption) (*ClaimSlotReply, error) {
	out := new(ClaimSlotReply)
	err := c.cc.Invoke(ctx, CronService_ClaimSlot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) UnclaimSlot(ctx context.Context, in *UnclaimSlotRequest, opts ...grpc.CallOption) (*UnclaimSlotReply, error) {
	out := new(UnclaimSlotReply)
	err := c.cc.Invoke(ctx, CronService_UnclaimSlot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) RecordFire(ctx context.Context, in *RecordFireRequest, opts ...grpc.CallOption) (*RecordFireReply, error) {
	out := new(RecordFireReply)
	err := c.cc.Invoke(ctx, CronService_RecordFire_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronServiceClient) MarkFired(ctx context.Context, in *MarkFiredRequest, opts ...grpc.CallOption) (*MarkFiredReply, error) {
	out := new(MarkFiredReply)
	err := c.cc.Invoke(ctx, CronService_MarkFired_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CronServiceServer is the server API for CronService service.
// All implementations must embed UnimplementedCronServiceServer
// for forward compatibility
type CronServiceServer interface {
	Get(context.Context, *GetRequest) (*GetReply, error)
	List(context.Context, *ListRequest) (*ListReply, error)
	Put(context.Context, *PutRequest) (*PutReply, error)
	PutIfAbsent(context.Context, *PutIfAbsentRequest) (*PutReply, error)
	Merge(context.Context, *MergeRequest) (*MergeReply, error)
	Delete(context.Context, *DeleteRequest) (*DeleteReply, error)
	Take(context.Context, *TakeRequest) (*TakeReply, error)
	ListDue(context.Context, *ListDueRequest) (*ListDueReply, error)
	ClaimSlot(context.Context, *ClaimSlotRequest) (*ClaimSlotReply, error)
	UnclaimSlot(context.Context, *UnclaimSlotRequest) (*UnclaimSlotReply, error)
	RecordFire(context.Context, *RecordFireRequest) (*RecordFireReply, error)
	MarkFired(context.Context, *MarkFiredRequest) (*MarkFiredReply, error)
	mustEmbedUnimplementedCronServiceServer()
}

// UnimplementedCronServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCronServiceServer struct {
}

func (UnimplementedCronServiceServer) Get(context.Context, *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCronServiceServer) List(context.Context, *ListRequest) (*ListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCronServiceServer) Put(context.Context, *PutRequest) (*PutReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedCronServiceServer) PutIfAbsent(context.Context, *PutIfAbsentRequest) (*PutReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutIfAbsent not implemented")
}
func (UnimplementedCronServiceServer) Merge(context.Context, *MergeRequest) (*MergeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Merge not implemented")
}
func (UnimplementedCronServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCronServiceServer) Take(context.Context, *TakeRequest) (*TakeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Take not implemented")
}
func (UnimplementedCronServiceServer) ListDue(context.Context, *ListDueRequest) (*ListDueReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDue not implemented")
}
func (UnimplementedCronServiceServer) ClaimSlot(context.Context, *ClaimSlotRequest) (*ClaimSlotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimSlot not implemented")
}
func (UnimplementedCronServiceServer) UnclaimSlot(context.Context, *UnclaimSlotRequest) (*UnclaimSlotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnclaimSlot not implemented")
}
func (UnimplementedCronServiceServer) RecordFire(context.Context, *RecordFireRequest) (*RecordFireReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordFire not implemented")
}
func (UnimplementedCronServiceServer) MarkFired(context.Context, *MarkFiredRequest) (*MarkFiredReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkFired not implemented")
}
func (UnimplementedCronServiceServer) mustEmbedUnimplementedCronServiceServer() {}

// UnsafeCronServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CronServiceServer will
// result in compilation errors.
type UnsafeCronServiceServer interface {
	mustEmbedUnimplementedCronServiceServer()
}

func RegisterCronServiceServer(s grpc.ServiceRegistrar, srv CronServiceServer) {
	s.RegisterService(&CronService_ServiceDesc, srv)
}

func _CronService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_PutIfAbsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutIfAbsentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).PutIfAbsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_PutIfAbsent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).PutIfAbsent(ctx, req.(*PutIfAbsentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_Merge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).Merge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_Merge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).Merge(ctx, req.(*MergeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_Take_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).Take(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_Take_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).Take(ctx, req.(*TakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_ListDue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).ListDue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_ListDue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).ListDue(ctx, req.(*ListDueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_ClaimSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).ClaimSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_ClaimSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).ClaimSlot(ctx, req.(*ClaimSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_UnclaimSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnclaimSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).UnclaimSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_UnclaimSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).UnclaimSlot(ctx, req.(*UnclaimSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_RecordFire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordFireRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).RecordFire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_RecordFire_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).RecordFire(ctx, req.(*RecordFireRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronService_MarkFired_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkFiredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronServiceServer).MarkFired(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronService_MarkFired_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronServiceServer).MarkFired(ctx, req.(*MarkFiredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CronService_ServiceDesc is the grpc.ServiceDesc for CronService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CronService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qm.cron.v1.CronService",
	HandlerType: (*CronServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CronService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CronService_List_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _CronService_Put_Handler,
		},
		{
			MethodName: "PutIfAbsent",
			Handler:    _CronService_PutIfAbsent_Handler,
		},
		{
			MethodName: "Merge",
			Handler:    _CronService_Merge_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CronService_Delete_Handler,
		},
		{
			MethodName: "Take",
			Handler:    _CronService_Take_Handler,
		},
		{
			MethodName: "ListDue",
			Handler:    _CronService_ListDue_Handler,
		},
		{
			MethodName: "ClaimSlot",
			Handler:    _CronService_ClaimSlot_Handler,
		},
		{
			MethodName: "UnclaimSlot",
			Handler:    _CronService_UnclaimSlot_Handler,
		},
		{
			MethodName: "RecordFire",
			Handler:    _CronService_RecordFire_Handler,
		},
		{
			MethodName: "MarkFired",
			Handler:    _CronService_MarkFired_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/qm/cron/v1/cron.proto",
}
