// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v7.35.1
// source: api/qm/deployment/v1/deployment.proto

package deploymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_deployment_v1_deployment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_deployment_v1_deployment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_qm_deployment_v1_deployment_proto_rawDescGZIP(), []int{0}
}

type GetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found   bool   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_deployment_v1_deployment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_deployment_v1_deployment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_api_qm_deployment_v1_deployment_proto_rawDescGZIP(), []int{1}
}

func (x *GetReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetReply) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PutIfAbsentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *PutIfAbsentRequest) Reset() {
	*x = PutIfAbsentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_deployment_v1_deployment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutIfAbsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutIfAbsentRequest) ProtoMessage() {}

func (x *PutIfAbsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_deployment_v1_deployment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutIfAbsentRequest.ProtoReflect.Descriptor instead.
func (*PutIfAbsentRequest) Descriptor() ([]byte, []int) {
	return file_api_qm_deployment_v1_deployment_proto_rawDescGZIP(), []int{2}
}

func (x *PutIfAbsentRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PutIfAbsentReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *PutIfAbsentReply) Reset() {
	*x = PutIfAbsentReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_deployment_v1_deployment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutIfAbsentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutIfAbsentReply) ProtoMessage() {}

func (x *PutIfAbsentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_deployment_v1_deployment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutIfAbsentReply.ProtoReflect.Descriptor instead.
func (*PutIfAbsentReply) Descriptor() ([]byte, []int) {
	return file_api_qm_deployment_v1_deployment_proto_rawDescGZIP(), []int{3}
}

func (x *PutIfAbsentReply) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Replace the current document only if it still matches expected_payload under
// PostgreSQL JSONB equality. On a conflict, payload contains the current
// document so the caller can recompute its update without a blind overwrite.
type CompareAndSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExpectedPayload []byte `protobuf:"bytes,1,opt,name=expected_payload,json=expectedPayload,proto3" json:"expected_payload,omitempty"`
	Payload         []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *CompareAndSetRequest) Reset() {
	*x = CompareAndSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_deployment_v1_deployment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompareAndSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareAndSetRequest) ProtoMessage() {}

func (x *CompareAndSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_deployment_v1_deployment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareAndSetRequest.ProtoReflect.Descriptor instead.
func (*CompareAndSetRequest) Descriptor() ([]byte, []int) {
	return file_api_qm_deployment_v1_deployment_proto_rawDescGZIP(), []int{4}
}

func (x *CompareAndSetRequest) GetExpectedPayload() []byte {
	if x != nil {
		return x.ExpectedPayload
	}
	return nil
}

func (x *CompareAndSetRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CompareAndSetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found   bool   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Updated bool   `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *CompareAndSetReply) Reset() {
	*x = CompareAndSetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_qm_deployment_v1_deployment_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompareAndSetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareAndSetReply) ProtoMessage() {}

func (x *CompareAndSetReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_qm_deployment_v1_deployment_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareAndSetReply.ProtoReflect.Descriptor instead.
func (*CompareAndSetReply) Descriptor() ([]byte, []int) {
	return file_api_qm_deployment_v1_deployment_proto_rawDescGZIP(), []int{5}
}

func (x *CompareAndSetReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *CompareAndSetReply) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

func (x *CompareAndSetReply) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_api_qm_deployment_v1_deployment_proto protoreflect.FileDescriptor

var file_api_qm_deployment_v1_deployment_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x71, 0x6d, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x71, 0x6d, 0x2e, 0x64, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x22, 0x0c, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x2e, 0x0a, 0x12, 0x50, 0x75, 0x74, 0x49, 0x66, 0x41, 0x62, 0x73, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x2c, 0x0a, 0x10, 0x50, 0x75, 0x74, 0x49, 0x66, 0x41, 0x62, 0x73, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x5b, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x41, 0x6e, 0x64, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x65, 0x78, 0x70,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0f, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x5e,
	0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x41, 0x6e, 0x64, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0x91,
	0x02, 0x0a, 0x16, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x61, 0x79,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x03, 0x47, 0x65, 0x74,
	0x12, 0x1c, 0x2e, 0x71, 0x6d, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x71, 0x6d, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x57, 0x0a, 0x0b, 0x50, 0x75,
	0x74, 0x49, 0x66, 0x41, 0x62, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x24, 0x2e, 0x71, 0x6d, 0x2e, 0x64,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74,
	0x49, 0x66, 0x41, 0x62, 0x73, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x71, 0x6d, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x49, 0x66, 0x41, 0x62, 0x73, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x5d, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x41, 0x6e,
	0x64, 0x53, 0x65, 0x74, 0x12, 0x26, 0x2e, 0x71, 0x6d, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x41,
	0x6e, 0x64, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x71,
	0x6d, 0x2e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x41, 0x6e, 0x64, 0x53, 0x65, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x68, 0x65, 0x6a, 0x77, 0x2f, 0x71, 0x6d, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x71, 0x6d, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_qm_deployment_v1_deployment_proto_rawDescOnce sync.Once
	file_api_qm_deployment_v1_deployment_proto_rawDescData = file_api_qm_deployment_v1_deployment_proto_rawDesc
)

func file_api_qm_deployment_v1_deployment_proto_rawDescGZIP() []byte {
	file_api_qm_deployment_v1_deployment_proto_rawDescOnce.Do(func() {
		file_api_qm_deployment_v1_deployment_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_qm_deployment_v1_deployment_proto_rawDescData)
	})
	return file_api_qm_deployment_v1_deployment_proto_rawDescData
}

var file_api_qm_deployment_v1_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_qm_deployment_v1_deployment_proto_goTypes = []interface{}{
	(*GetRequest)(nil),           // 0: qm.deployment.v1.GetRequest
	(*GetReply)(nil),             // 1: qm.deployment.v1.GetReply
	(*PutIfAbsentRequest)(nil),   // 2: qm.deployment.v1.PutIfAbsentRequest
	(*PutIfAbsentReply)(nil),     // 3: qm.deployment.v1.PutIfAbsentReply
	(*CompareAndSetRequest)(nil), // 4: qm.deployment.v1.CompareAndSetRequest
	(*CompareAndSetReply)(nil),   // 5: qm.deployment.v1.CompareAndSetReply
}
var file_api_qm_deployment_v1_deployment_proto_depIdxs = []int32{
	0, // 0: qm.deployment.v1.DeploymentLayerService.Get:input_type -> qm.deployment.v1.GetRequest
	2, // 1: qm.deployment.v1.DeploymentLayerService.PutIfAbsent:input_type -> qm.deployment.v1.PutIfAbsentRequest
	4, // 2: qm.deployment.v1.DeploymentLayerService.CompareAndSet:input_type -> qm.deployment.v1.CompareAndSetRequest
	1, // 3: qm.deployment.v1.DeploymentLayerService.Get:output_type -> qm.deployment.v1.GetReply
	3, // 4: qm.deployment.v1.DeploymentLayerService.PutIfAbsent:output_type -> qm.deployment.v1.PutIfAbsentReply
	5, // 5: qm.deployment.v1.DeploymentLayerService.CompareAndSet:output_type -> qm.deployment.v1.CompareAndSetReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_qm_deployment_v1_deployment_proto_init() }
func file_api_qm_deployment_v1_deployment_proto_init() {
	if File_api_qm_deployment_v1_deployment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_qm_deployment_v1_deployment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_deployment_v1_deployment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_deployment_v1_deployment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutIfAbsentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_deployment_v1_deployment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutIfAbsentReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_deployment_v1_deployment_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompareAndSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_qm_deployment_v1_deployment_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompareAndSetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_qm_deployment_v1_deployment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_qm_deployment_v1_deployment_proto_goTypes,
		DependencyIndexes: file_api_qm_deployment_v1_deployment_proto_depIdxs,
		MessageInfos:      file_api_qm_deployment_v1_deployment_proto_msgTypes,
	}.Build()
	File_api_qm_deployment_v1_deployment_proto = out.File
	file_api_qm_deployment_v1_deployment_proto_rawDesc = nil
	file_api_qm_deployment_v1_deployment_proto_goTypes = nil
	file_api_qm_deployment_v1_deployment_proto_depIdxs = nil
}
