// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: knowledge/v1/knowledge.proto

package knowledgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallerContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ScopeId       string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	ScopeKind     string                 `protobuf:"bytes,3,opt,name=scope_kind,json=scopeKind,proto3" json:"scope_kind,omitempty"`
	ActorId       string                 `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Capabilities  []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,7,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallerContext) Reset() {
	*x = CallerContext{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallerContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallerContext) ProtoMessage() {}

func (x *CallerContext) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallerContext.ProtoReflect.Descriptor instead.
func (*CallerContext) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *CallerContext) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CallerContext) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *CallerContext) GetScopeKind() string {
	if x != nil {
		return x.ScopeKind
	}
	return ""
}

func (x *CallerContext) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *CallerContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CallerContext) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *CallerContext) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type ScopeRef struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExternalScopeId string                 `protobuf:"bytes,1,opt,name=external_scope_id,json=externalScopeId,proto3" json:"external_scope_id,omitempty"`
	Kind            string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScopeRef) Reset() {
	*x = ScopeRef{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeRef) ProtoMessage() {}

func (x *ScopeRef) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeRef.ProtoReflect.Descriptor instead.
func (*ScopeRef) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *ScopeRef) GetExternalScopeId() string {
	if x != nil {
		return x.ExternalScopeId
	}
	return ""
}

func (x *ScopeRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type EnsureScopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *ScopeRef              `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureScopeRequest) Reset() {
	*x = EnsureScopeRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureScopeRequest) ProtoMessage() {}

func (x *EnsureScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureScopeRequest.ProtoReflect.Descriptor instead.
func (*EnsureScopeRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *EnsureScopeRequest) GetScope() *ScopeRef {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *EnsureScopeRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *EnsureScopeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *ScopeRef              `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Caller        *CallerContext         `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusRequest) GetScope() *ScopeRef {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *GetStatusRequest) GetCaller() *CallerContext {
	if x != nil {
		return x.Caller
	}
	return nil
}

type ScopeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *ScopeRef              `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	WikiPageCount int64                  `protobuf:"varint,6,opt,name=wiki_page_count,json=wikiPageCount,proto3" json:"wiki_page_count,omitempty"`
	SourceCount   int64                  `protobuf:"varint,7,opt,name=source_count,json=sourceCount,proto3" json:"source_count,omitempty"`
	Ready         bool                   `protobuf:"varint,8,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeStatus) Reset() {
	*x = ScopeStatus{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeStatus) ProtoMessage() {}

func (x *ScopeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeStatus.ProtoReflect.Descriptor instead.
func (*ScopeStatus) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *ScopeStatus) GetScope() *ScopeRef {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ScopeStatus) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ScopeStatus) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ScopeStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScopeStatus) GetWikiPageCount() int64 {
	if x != nil {
		return x.WikiPageCount
	}
	return 0
}

func (x *ScopeStatus) GetSourceCount() int64 {
	if x != nil {
		return x.SourceCount
	}
	return 0
}

func (x *ScopeStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type QueryRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Scope               *ScopeRef              `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Caller              *CallerContext         `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Question            string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	ConversationContext string                 `protobuf:"bytes,4,opt,name=conversation_context,json=conversationContext,proto3" json:"conversation_context,omitempty"`
	Limit               int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *QueryRequest) GetScope() *ScopeRef {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *QueryRequest) GetCaller() *CallerContext {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *QueryRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *QueryRequest) GetConversationContext() string {
	if x != nil {
		return x.ConversationContext
	}
	return ""
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Question                string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Answer                  string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	Status                  string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	SuggestedWritebackTitle string                 `protobuf:"bytes,4,opt,name=suggested_writeback_title,json=suggestedWritebackTitle,proto3" json:"suggested_writeback_title,omitempty"`
	Citations               []*QueryCitation       `protobuf:"bytes,5,rep,name=citations,proto3" json:"citations,omitempty"`
	Results                 []*QueryResult         `protobuf:"bytes,6,rep,name=results,proto3" json:"results,omitempty"`
	IncompleteReason        string                 `protobuf:"bytes,7,opt,name=incomplete_reason,json=incompleteReason,proto3" json:"incomplete_reason,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *QueryResponse) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *QueryResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *QueryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryResponse) GetSuggestedWritebackTitle() string {
	if x != nil {
		return x.SuggestedWritebackTitle
	}
	return ""
}

func (x *QueryResponse) GetCitations() []*QueryCitation {
	if x != nil {
		return x.Citations
	}
	return nil
}

func (x *QueryResponse) GetResults() []*QueryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *QueryResponse) GetIncompleteReason() string {
	if x != nil {
		return x.IncompleteReason
	}
	return ""
}

type QueryCitation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCitation) Reset() {
	*x = QueryCitation{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCitation) ProtoMessage() {}

func (x *QueryCitation) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCitation.ProtoReflect.Descriptor instead.
func (*QueryCitation) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *QueryCitation) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *QueryCitation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QueryCitation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippet       string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{8}
}

func (x *QueryResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *QueryResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QueryResult) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *QueryResult) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QueryResult) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *ScopeRef              `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Caller        *CallerContext         `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{9}
}

func (x *SearchRequest) GetScope() *ScopeRef {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *SearchRequest) GetCaller() *CallerContext {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*QueryResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{10}
}

func (x *SearchResponse) GetResults() []*QueryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReadDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *ScopeRef              `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Caller        *CallerContext         `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDocumentRequest) Reset() {
	*x = ReadDocumentRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDocumentRequest) ProtoMessage() {}

func (x *ReadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDocumentRequest.ProtoReflect.Descriptor instead.
func (*ReadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{11}
}

func (x *ReadDocumentRequest) GetScope() *ScopeRef {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ReadDocumentRequest) GetCaller() *CallerContext {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *ReadDocumentRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{12}
}

func (x *Document) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Document) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_knowledge_v1_knowledge_proto protoreflect.FileDescriptor

const file_knowledge_v1_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x1cknowledge/v1/knowledge.proto\x12\fknowledge.v1\"\xe6\x01\n" +
	"\rCallerContext\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\x12\x1d\n" +
	"\n" +
	"scope_kind\x18\x03 \x01(\tR\tscopeKind\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12&\n" +
	"\x0fexpires_at_unix\x18\a \x01(\x03R\rexpiresAtUnix\"J\n" +
	"\bScopeRef\x12*\n" +
	"\x11external_scope_id\x18\x01 \x01(\tR\x0fexternalScopeId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"m\n" +
	"\x12EnsureScopeRequest\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.knowledge.v1.ScopeRefR\x05scope\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"u\n" +
	"\x10GetStatusRequest\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.knowledge.v1.ScopeRefR\x05scope\x123\n" +
	"\x06caller\x18\x02 \x01(\v2\x1b.knowledge.v1.CallerContextR\x06caller\"\xf6\x01\n" +
	"\vScopeStatus\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.knowledge.v1.ScopeRefR\x05scope\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12!\n" +
	"\fproject_name\x18\x03 \x01(\tR\vprojectName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12&\n" +
	"\x0fwiki_page_count\x18\x06 \x01(\x03R\rwikiPageCount\x12!\n" +
	"\fsource_count\x18\a \x01(\x03R\vsourceCount\x12\x14\n" +
	"\x05ready\x18\b \x01(\bR\x05ready\"\xd6\x01\n" +
	"\fQueryRequest\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.knowledge.v1.ScopeRefR\x05scope\x123\n" +
	"\x06caller\x18\x02 \x01(\v2\x1b.knowledge.v1.CallerContextR\x06caller\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x121\n" +
	"\x14conversation_context\x18\x04 \x01(\tR\x13conversationContext\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\xb4\x02\n" +
	"\rQueryResponse\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12:\n" +
	"\x19suggested_writeback_title\x18\x04 \x01(\tR\x17suggestedWritebackTitle\x129\n" +
	"\tcitations\x18\x05 \x03(\v2\x1b.knowledge.v1.QueryCitationR\tcitations\x123\n" +
	"\aresults\x18\x06 \x03(\v2\x19.knowledge.v1.QueryResultR\aresults\x12+\n" +
	"\x11incomplete_reason\x18\a \x01(\tR\x10incompleteReason\"M\n" +
	"\rQueryCitation\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\"{\n" +
	"\vQueryResult\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\"\x9e\x01\n" +
	"\rSearchRequest\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.knowledge.v1.ScopeRefR\x05scope\x123\n" +
	"\x06caller\x18\x02 \x01(\v2\x1b.knowledge.v1.CallerContextR\x06caller\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"E\n" +
	"\x0eSearchResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.knowledge.v1.QueryResultR\aresults\"\x8c\x01\n" +
	"\x13ReadDocumentRequest\x12,\n" +
	"\x05scope\x18\x01 \x01(\v2\x16.knowledge.v1.ScopeRefR\x05scope\x123\n" +
	"\x06caller\x18\x02 \x01(\v2\x1b.knowledge.v1.CallerContextR\x06caller\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"b\n" +
	"\bDocument\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent2\xf5\x02\n" +
	"\rKnowledgeCore\x12J\n" +
	"\vEnsureScope\x12 .knowledge.v1.EnsureScopeRequest\x1a\x19.knowledge.v1.ScopeStatus\x12F\n" +
	"\tGetStatus\x12\x1e.knowledge.v1.GetStatusRequest\x1a\x19.knowledge.v1.ScopeStatus\x12@\n" +
	"\x05Query\x12\x1a.knowledge.v1.QueryRequest\x1a\x1b.knowledge.v1.QueryResponse\x12C\n" +
	"\x06Search\x12\x1b.knowledge.v1.SearchRequest\x1a\x1c.knowledge.v1.SearchResponse\x12I\n" +
	"\fReadDocument\x12!.knowledge.v1.ReadDocumentRequest\x1a\x16.knowledge.v1.DocumentBJZHgithub.com/hejw/knowledge-core/internal/grpcapi/knowledge/v1;knowledgev1b\x06proto3"

var (
	file_knowledge_v1_knowledge_proto_rawDescOnce sync.Once
	file_knowledge_v1_knowledge_proto_rawDescData []byte
)

func file_knowledge_v1_knowledge_proto_rawDescGZIP() []byte {
	file_knowledge_v1_knowledge_proto_rawDescOnce.Do(func() {
		file_knowledge_v1_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_knowledge_v1_knowledge_proto_rawDesc), len(file_knowledge_v1_knowledge_proto_rawDesc)))
	})
	return file_knowledge_v1_knowledge_proto_rawDescData
}

var file_knowledge_v1_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_knowledge_v1_knowledge_proto_goTypes = []any{
	(*CallerContext)(nil),       // 0: knowledge.v1.CallerContext
	(*ScopeRef)(nil),            // 1: knowledge.v1.ScopeRef
	(*EnsureScopeRequest)(nil),  // 2: knowledge.v1.EnsureScopeRequest
	(*GetStatusRequest)(nil),    // 3: knowledge.v1.GetStatusRequest
	(*ScopeStatus)(nil),         // 4: knowledge.v1.ScopeStatus
	(*QueryRequest)(nil),        // 5: knowledge.v1.QueryRequest
	(*QueryResponse)(nil),       // 6: knowledge.v1.QueryResponse
	(*QueryCitation)(nil),       // 7: knowledge.v1.QueryCitation
	(*QueryResult)(nil),         // 8: knowledge.v1.QueryResult
	(*SearchRequest)(nil),       // 9: knowledge.v1.SearchRequest
	(*SearchResponse)(nil),      // 10: knowledge.v1.SearchResponse
	(*ReadDocumentRequest)(nil), // 11: knowledge.v1.ReadDocumentRequest
	(*Document)(nil),            // 12: knowledge.v1.Document
}
var file_knowledge_v1_knowledge_proto_depIdxs = []int32{
	1,  // 0: knowledge.v1.EnsureScopeRequest.scope:type_name -> knowledge.v1.ScopeRef
	1,  // 1: knowledge.v1.GetStatusRequest.scope:type_name -> knowledge.v1.ScopeRef
	0,  // 2: knowledge.v1.GetStatusRequest.caller:type_name -> knowledge.v1.CallerContext
	1,  // 3: knowledge.v1.ScopeStatus.scope:type_name -> knowledge.v1.ScopeRef
	1,  // 4: knowledge.v1.QueryRequest.scope:type_name -> knowledge.v1.ScopeRef
	0,  // 5: knowledge.v1.QueryRequest.caller:type_name -> knowledge.v1.CallerContext
	7,  // 6: knowledge.v1.QueryResponse.citations:type_name -> knowledge.v1.QueryCitation
	8,  // 7: knowledge.v1.QueryResponse.results:type_name -> knowledge.v1.QueryResult
	1,  // 8: knowledge.v1.SearchRequest.scope:type_name -> knowledge.v1.ScopeRef
	0,  // 9: knowledge.v1.SearchRequest.caller:type_name -> knowledge.v1.CallerContext
	8,  // 10: knowledge.v1.SearchResponse.results:type_name -> knowledge.v1.QueryResult
	1,  // 11: knowledge.v1.ReadDocumentRequest.scope:type_name -> knowledge.v1.ScopeRef
	0,  // 12: knowledge.v1.ReadDocumentRequest.caller:type_name -> knowledge.v1.CallerContext
	2,  // 13: knowledge.v1.KnowledgeCore.EnsureScope:input_type -> knowledge.v1.EnsureScopeRequest
	3,  // 14: knowledge.v1.KnowledgeCore.GetStatus:input_type -> knowledge.v1.GetStatusRequest
	5,  // 15: knowledge.v1.KnowledgeCore.Query:input_type -> knowledge.v1.QueryRequest
	9,  // 16: knowledge.v1.KnowledgeCore.Search:input_type -> knowledge.v1.SearchRequest
	11, // 17: knowledge.v1.KnowledgeCore.ReadDocument:input_type -> knowledge.v1.ReadDocumentRequest
	4,  // 18: knowledge.v1.KnowledgeCore.EnsureScope:output_type -> knowledge.v1.ScopeStatus
	4,  // 19: knowledge.v1.KnowledgeCore.GetStatus:output_type -> knowledge.v1.ScopeStatus
	6,  // 20: knowledge.v1.KnowledgeCore.Query:output_type -> knowledge.v1.QueryResponse
	10, // 21: knowledge.v1.KnowledgeCore.Search:output_type -> knowledge.v1.SearchResponse
	12, // 22: knowledge.v1.KnowledgeCore.ReadDocument:output_type -> knowledge.v1.Document
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_knowledge_v1_knowledge_proto_init() }
func file_knowledge_v1_knowledge_proto_init() {
	if File_knowledge_v1_knowledge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_knowledge_v1_knowledge_proto_rawDesc), len(file_knowledge_v1_knowledge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_knowledge_v1_knowledge_proto_goTypes,
		DependencyIndexes: file_knowledge_v1_knowledge_proto_depIdxs,
		MessageInfos:      file_knowledge_v1_knowledge_proto_msgTypes,
	}.Build()
	File_knowledge_v1_knowledge_proto = out.File
	file_knowledge_v1_knowledge_proto_goTypes = nil
	file_knowledge_v1_knowledge_proto_depIdxs = nil
}
