// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.35.1
// source: knowledge/v1/knowledge.proto

package knowledgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowledgeCore_EnsureScope_FullMethodName  = "/knowledge.v1.KnowledgeCore/EnsureScope"
	KnowledgeCore_GetStatus_FullMethodName    = "/knowledge.v1.KnowledgeCore/GetStatus"
	KnowledgeCore_Query_FullMethodName        = "/knowledge.v1.KnowledgeCore/Query"
	KnowledgeCore_Search_FullMethodName       = "/knowledge.v1.KnowledgeCore/Search"
	KnowledgeCore_ReadDocument_FullMethodName = "/knowledge.v1.KnowledgeCore/ReadDocument"
)

// KnowledgeCoreClient is the client API for KnowledgeCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KnowledgeCoreClient interface {
	// EnsureScope is a control-plane operation. It never accepts a filesystem
	// path from the caller; the server derives the project root from its
	// configured scope root or an existing administrator binding.
	EnsureScope(ctx context.Context, in *EnsureScopeRequest, opts ...grpc.CallOption) (*ScopeStatus, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*ScopeStatus, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	ReadDocument(ctx context.Context, in *ReadDocumentRequest, opts ...grpc.CallOption) (*Document, error)
}

type knowledgeCoreClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeCoreClient(cc grpc.ClientConnInterface) KnowledgeCoreClient {
	return &knowledgeCoreClient{cc}
}

func (c *knowledgeCoreClient) EnsureScope(ctx context.Context, in *EnsureScopeRequest, opts ...grpc.CallOption) (*ScopeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScopeStatus)
	err := c.cc.Invoke(ctx, KnowledgeCore_EnsureScope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeCoreClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*ScopeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScopeStatus)
	err := c.cc.Invoke(ctx, KnowledgeCore_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeCoreClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, KnowledgeCore_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeCoreClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, KnowledgeCore_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeCoreClient) ReadDocument(ctx context.Context, in *ReadDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, KnowledgeCore_ReadDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeCoreServer is the server API for KnowledgeCore service.
// All implementations must embed UnimplementedKnowledgeCoreServer
// for forward compatibility.
type KnowledgeCoreServer interface {
	// EnsureScope is a control-plane operation. It never accepts a filesystem
	// path from the caller; the server derives the project root from its
	// configured scope root or an existing administrator binding.
	EnsureScope(context.Context, *EnsureScopeRequest) (*ScopeStatus, error)
	GetStatus(context.Context, *GetStatusRequest) (*ScopeStatus, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	ReadDocument(context.Context, *ReadDocumentRequest) (*Document, error)
	mustEmbedUnimplementedKnowledgeCoreServer()
}

// UnimplementedKnowledgeCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeCoreServer struct{}

func (UnimplementedKnowledgeCoreServer) EnsureScope(context.Context, *EnsureScopeRequest) (*ScopeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureScope not implemented")
}
func (UnimplementedKnowledgeCoreServer) GetStatus(context.Context, *GetStatusRequest) (*ScopeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedKnowledgeCoreServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedKnowledgeCoreServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedKnowledgeCoreServer) ReadDocument(context.Context, *ReadDocumentRequest) (*Document, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadDocument not implemented")
}
func (UnimplementedKnowledgeCoreServer) mustEmbedUnimplementedKnowledgeCoreServer() {}
func (UnimplementedKnowledgeCoreServer) testEmbeddedByValue()                       {}

// UnsafeKnowledgeCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeCoreServer will
// result in compilation errors.
type UnsafeKnowledgeCoreServer interface {
	mustEmbedUnimplementedKnowledgeCoreServer()
}

func RegisterKnowledgeCoreServer(s grpc.ServiceRegistrar, srv KnowledgeCoreServer) {
	// If the following call panics, it indicates UnimplementedKnowledgeCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeCore_ServiceDesc, srv)
}

func _KnowledgeCore_EnsureScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureScopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeCoreServer).EnsureScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeCore_EnsureScope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeCoreServer).EnsureScope(ctx, req.(*EnsureScopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeCore_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeCoreServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeCore_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeCoreServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeCore_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeCoreServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeCore_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeCoreServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeCore_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeCoreServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeCore_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeCoreServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeCore_ReadDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeCoreServer).ReadDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeCore_ReadDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeCoreServer).ReadDocument(ctx, req.(*ReadDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeCore_ServiceDesc is the grpc.ServiceDesc for KnowledgeCore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeCore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knowledge.v1.KnowledgeCore",
	HandlerType: (*KnowledgeCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureScope",
			Handler:    _KnowledgeCore_EnsureScope_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _KnowledgeCore_GetStatus_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _KnowledgeCore_Query_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _KnowledgeCore_Search_Handler,
		},
		{
			MethodName: "ReadDocument",
			Handler:    _KnowledgeCore_ReadDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "knowledge/v1/knowledge.proto",
}
