// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: api/knowledge/v1/knowledge.proto

package knowledgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	KnowledgeCore_EnsureScope_FullMethodName     = "/knowledge.v1.KnowledgeCore/EnsureScope"
	KnowledgeCore_GetStatus_FullMethodName       = "/knowledge.v1.KnowledgeCore/GetStatus"
	KnowledgeCore_Query_FullMethodName           = "/knowledge.v1.KnowledgeCore/Query"
	KnowledgeCore_Search_FullMethodName          = "/knowledge.v1.KnowledgeCore/Search"
	KnowledgeCore_ReadDocument_FullMethodName    = "/knowledge.v1.KnowledgeCore/ReadDocument"
	KnowledgeCore_IngestSource_FullMethodName    = "/knowledge.v1.KnowledgeCore/IngestSource"
	KnowledgeCore_SaveQueryAnswer_FullMethodName = "/knowledge.v1.KnowledgeCore/SaveQueryAnswer"
)

// KnowledgeCoreClient is the client API for KnowledgeCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KnowledgeCoreClient interface {
	EnsureScope(ctx context.Context, in *EnsureScopeRequest, opts ...grpc.CallOption) (*ScopeStatus, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*ScopeStatus, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	ReadDocument(ctx context.Context, in *ReadDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	IngestSource(ctx context.Context, in *IngestSourceRequest, opts ...grpc.CallOption) (*IngestSourceReply, error)
	SaveQueryAnswer(ctx context.Context, in *SaveQueryAnswerRequest, opts ...grpc.CallOption) (*SaveQueryAnswerReply, error)
}

type knowledgeCoreClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeCoreClient(cc grpc.ClientConnInterface) KnowledgeCoreClient {
	return &knowledgeCoreClient{cc}
}

func (c *knowledgeCoreClient) EnsureScope(ctx context.Context, in *EnsureScopeRequest, opts ...grpc.CallOption) (*ScopeStatus, error) {
	out := new(ScopeStatus)
	err := c.cc.Invoke(ctx, KnowledgeCore_EnsureScope_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeCoreClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*ScopeStatus, error) {
	out := new(ScopeStatus)
	err := c.cc.Invoke(ctx, KnowledgeCore_GetStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeCoreClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, KnowledgeCore_Query_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeCoreClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, KnowledgeCore_Search_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeCoreClient) ReadDocument(ctx context.Context, in *ReadDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, KnowledgeCore_ReadDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeCoreClient) IngestSource(ctx context.Context, in *IngestSourceRequest, opts ...grpc.CallOption) (*IngestSourceReply, error) {
	out := new(IngestSourceReply)
	err := c.cc.Invoke(ctx, KnowledgeCore_IngestSource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeCoreClient) SaveQueryAnswer(ctx context.Context, in *SaveQueryAnswerRequest, opts ...grpc.CallOption) (*SaveQueryAnswerReply, error) {
	out := new(SaveQueryAnswerReply)
	err := c.cc.Invoke(ctx, KnowledgeCore_SaveQueryAnswer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeCoreServer is the server API for KnowledgeCore service.
// All implementations must embed UnimplementedKnowledgeCoreServer
// for forward compatibility
type KnowledgeCoreServer interface {
	EnsureScope(context.Context, *EnsureScopeRequest) (*ScopeStatus, error)
	GetStatus(context.Context, *GetStatusRequest) (*ScopeStatus, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	ReadDocument(context.Context, *ReadDocumentRequest) (*Document, error)
	IngestSource(context.Context, *IngestSourceRequest) (*IngestSourceReply, error)
	SaveQueryAnswer(context.Context, *SaveQueryAnswerRequest) (*SaveQueryAnswerReply, error)
	mustEmbedUnimplementedKnowledgeCoreServer()
}

// UnimplementedKnowledgeCoreServer must be embedded to have forward compatible implementations.
type UnimplementedKnowledgeCoreServer struct {
}

func (UnimplementedKnowledgeCoreServer) EnsureScope(context.Context, *EnsureScopeRequest) (*ScopeStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureScope not implemented")
}
func (UnimplementedKnowledgeCoreServer) GetStatus(context.Context, *GetStatusRequest) (*ScopeStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedKnowledgeCoreServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedKnowledgeCoreServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedKnowledgeCoreServer) ReadDocument(context.Context, *ReadDocumentRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadDocument not implemented")
}
func (UnimplementedKnowledgeCoreServer) IngestSource(context.Context, *IngestSourceRequest) (*IngestSourceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestSource not implemented")
}
func (UnimplementedKnowledgeCoreServer) SaveQueryAnswer(context.Context, *SaveQueryAnswerRequest) (*SaveQueryAnswerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveQueryAnswer not implemented")
}
func (UnimplementedKnowledgeCoreServer) mustEmbedUnimplementedKnowledgeCoreServer() {}

// UnsafeKnowledgeCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeCoreServer will
// result in compilation errors.
type UnsafeKnowledgeCoreServer interface {
	mustEmbedUnimplementedKnowledgeCoreServer()
}

func RegisterKnowledgeCoreServer(s grpc.ServiceRegistrar, srv KnowledgeCoreServer) {
	s.RegisterService(&KnowledgeCore_ServiceDesc, srv)
}

func _KnowledgeCore_EnsureScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureScopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeCoreServer).EnsureScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeCore_EnsureScope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeCoreServer).EnsureScope(ctx, req.(*EnsureScopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeCore_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeCoreServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeCore_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeCoreServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeCore_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeCoreServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeCore_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeCoreServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeCore_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeCoreServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeCore_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeCoreServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeCore_ReadDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeCoreServer).ReadDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeCore_ReadDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeCoreServer).ReadDocument(ctx, req.(*ReadDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeCore_IngestSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeCoreServer).IngestSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeCore_IngestSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeCoreServer).IngestSource(ctx, req.(*IngestSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeCore_SaveQueryAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveQueryAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeCoreServer).SaveQueryAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeCore_SaveQueryAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeCoreServer).SaveQueryAnswer(ctx, req.(*SaveQueryAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeCore_ServiceDesc is the grpc.ServiceDesc for KnowledgeCore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeCore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knowledge.v1.KnowledgeCore",
	HandlerType: (*KnowledgeCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureScope",
			Handler:    _KnowledgeCore_EnsureScope_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _KnowledgeCore_GetStatus_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _KnowledgeCore_Query_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _KnowledgeCore_Search_Handler,
		},
		{
			MethodName: "ReadDocument",
			Handler:    _KnowledgeCore_ReadDocument_Handler,
		},
		{
			MethodName: "IngestSource",
			Handler:    _KnowledgeCore_IngestSource_Handler,
		},
		{
			MethodName: "SaveQueryAnswer",
			Handler:    _KnowledgeCore_SaveQueryAnswer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/knowledge/v1/knowledge.proto",
}
