// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: api/qm/runner/v1/runner.proto

package runnerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RunnerService_EnqueueRun_FullMethodName             = "/qm.runner.v1.RunnerService/EnqueueRun"
	RunnerService_GetRun_FullMethodName                 = "/qm.runner.v1.RunnerService/GetRun"
	RunnerService_GetActiveRunForSession_FullMethodName = "/qm.runner.v1.RunnerService/GetActiveRunForSession"
	RunnerService_ListActiveSessionIDs_FullMethodName   = "/qm.runner.v1.RunnerService/ListActiveSessionIDs"
	RunnerService_ClaimRun_FullMethodName               = "/qm.runner.v1.RunnerService/ClaimRun"
	RunnerService_ClaimRunByID_FullMethodName           = "/qm.runner.v1.RunnerService/ClaimRunByID"
	RunnerService_HeartbeatRun_FullMethodName           = "/qm.runner.v1.RunnerService/HeartbeatRun"
	RunnerService_ReleaseRunLease_FullMethodName        = "/qm.runner.v1.RunnerService/ReleaseRunLease"
	RunnerService_FailRun_FullMethodName                = "/qm.runner.v1.RunnerService/FailRun"
	RunnerService_AppendRunEvent_FullMethodName         = "/qm.runner.v1.RunnerService/AppendRunEvent"
	RunnerService_CompleteRun_FullMethodName            = "/qm.runner.v1.RunnerService/CompleteRun"
	RunnerService_SignalRun_FullMethodName              = "/qm.runner.v1.RunnerService/SignalRun"
	RunnerService_TakePendingSignals_FullMethodName     = "/qm.runner.v1.RunnerService/TakePendingSignals"
	RunnerService_PendingSignalRunIDs_FullMethodName    = "/qm.runner.v1.RunnerService/PendingSignalRunIDs"
	RunnerService_PruneSignals_FullMethodName           = "/qm.runner.v1.RunnerService/PruneSignals"
	RunnerService_AppendRunActivity_FullMethodName      = "/qm.runner.v1.RunnerService/AppendRunActivity"
	RunnerService_ListRunActivity_FullMethodName        = "/qm.runner.v1.RunnerService/ListRunActivity"
	RunnerService_PruneRunActivity_FullMethodName       = "/qm.runner.v1.RunnerService/PruneRunActivity"
	RunnerService_ReapExpiredRuns_FullMethodName        = "/qm.runner.v1.RunnerService/ReapExpiredRuns"
)

// RunnerServiceClient is the client API for RunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunnerServiceClient interface {
	EnqueueRun(ctx context.Context, in *EnqueueRunRequest, opts ...grpc.CallOption) (*EnqueueRunReply, error)
	GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*GetRunReply, error)
	GetActiveRunForSession(ctx context.Context, in *GetActiveRunForSessionRequest, opts ...grpc.CallOption) (*GetRunReply, error)
	ListActiveSessionIDs(ctx context.Context, in *ListActiveSessionIDsRequest, opts ...grpc.CallOption) (*ListActiveSessionIDsReply, error)
	ClaimRun(ctx context.Context, in *ClaimRunRequest, opts ...grpc.CallOption) (*ClaimRunReply, error)
	ClaimRunByID(ctx context.Context, in *ClaimRunByIDRequest, opts ...grpc.CallOption) (*ClaimRunReply, error)
	HeartbeatRun(ctx context.Context, in *HeartbeatRunRequest, opts ...grpc.CallOption) (*HeartbeatRunReply, error)
	ReleaseRunLease(ctx context.Context, in *ReleaseRunLeaseRequest, opts ...grpc.CallOption) (*ReleaseRunLeaseReply, error)
	FailRun(ctx context.Context, in *FailRunRequest, opts ...grpc.CallOption) (*FailRunReply, error)
	AppendRunEvent(ctx context.Context, in *AppendRunEventRequest, opts ...grpc.CallOption) (*AppendRunEventReply, error)
	CompleteRun(ctx context.Context, in *CompleteRunRequest, opts ...grpc.CallOption) (*CompleteRunReply, error)
	SignalRun(ctx context.Context, in *SignalRunRequest, opts ...grpc.CallOption) (*SignalRunReply, error)
	TakePendingSignals(ctx context.Context, in *TakePendingSignalsRequest, opts ...grpc.CallOption) (*TakePendingSignalsReply, error)
	PendingSignalRunIDs(ctx context.Context, in *PendingSignalRunIDsRequest, opts ...grpc.CallOption) (*PendingSignalRunIDsReply, error)
	PruneSignals(ctx context.Context, in *PruneSignalsRequest, opts ...grpc.CallOption) (*PruneSignalsReply, error)
	AppendRunActivity(ctx context.Context, in *AppendRunActivityRequest, opts ...grpc.CallOption) (*AppendRunActivityReply, error)
	ListRunActivity(ctx context.Context, in *ListRunActivityRequest, opts ...grpc.CallOption) (*ListRunActivityReply, error)
	PruneRunActivity(ctx context.Context, in *PruneRunActivityRequest, opts ...grpc.CallOption) (*PruneRunActivityReply, error)
	ReapExpiredRuns(ctx context.Context, in *ReapExpiredRunsRequest, opts ...grpc.CallOption) (*ReapExpiredRunsReply, error)
}

type runnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerServiceClient(cc grpc.ClientConnInterface) RunnerServiceClient {
	return &runnerServiceClient{cc}
}

func (c *runnerServiceClient) EnqueueRun(ctx context.Context, in *EnqueueRunRequest, opts ...grpc.CallOption) (*EnqueueRunReply, error) {
	out := new(EnqueueRunReply)
	err := c.cc.Invoke(ctx, RunnerService_EnqueueRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*GetRunReply, error) {
	out := new(GetRunReply)
	err := c.cc.Invoke(ctx, RunnerService_GetRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) GetActiveRunForSession(ctx context.Context, in *GetActiveRunForSessionRequest, opts ...grpc.CallOption) (*GetRunReply, error) {
	out := new(GetRunReply)
	err := c.cc.Invoke(ctx, RunnerService_GetActiveRunForSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) ListActiveSessionIDs(ctx context.Context, in *ListActiveSessionIDsRequest, opts ...grpc.CallOption) (*ListActiveSessionIDsReply, error) {
	out := new(ListActiveSessionIDsReply)
	err := c.cc.Invoke(ctx, RunnerService_ListActiveSessionIDs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) ClaimRun(ctx context.Context, in *ClaimRunRequest, opts ...grpc.CallOption) (*ClaimRunReply, error) {
	out := new(ClaimRunReply)
	err := c.cc.Invoke(ctx, RunnerService_ClaimRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) ClaimRunByID(ctx context.Context, in *ClaimRunByIDRequest, opts ...grpc.CallOption) (*ClaimRunReply, error) {
	out := new(ClaimRunReply)
	err := c.cc.Invoke(ctx, RunnerService_ClaimRunByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) HeartbeatRun(ctx context.Context, in *HeartbeatRunRequest, opts ...grpc.CallOption) (*HeartbeatRunReply, error) {
	out := new(HeartbeatRunReply)
	err := c.cc.Invoke(ctx, RunnerService_HeartbeatRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) ReleaseRunLease(ctx context.Context, in *ReleaseRunLeaseRequest, opts ...grpc.CallOption) (*ReleaseRunLeaseReply, error) {
	out := new(ReleaseRunLeaseReply)
	err := c.cc.Invoke(ctx, RunnerService_ReleaseRunLease_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) FailRun(ctx context.Context, in *FailRunRequest, opts ...grpc.CallOption) (*FailRunReply, error) {
	out := new(FailRunReply)
	err := c.cc.Invoke(ctx, RunnerService_FailRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) AppendRunEvent(ctx context.Context, in *AppendRunEventRequest, opts ...grpc.CallOption) (*AppendRunEventReply, error) {
	out := new(AppendRunEventReply)
	err := c.cc.Invoke(ctx, RunnerService_AppendRunEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) CompleteRun(ctx context.Context, in *CompleteRunRequest, opts ...grpc.CallOption) (*CompleteRunReply, error) {
	out := new(CompleteRunReply)
	err := c.cc.Invoke(ctx, RunnerService_CompleteRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) SignalRun(ctx context.Context, in *SignalRunRequest, opts ...grpc.CallOption) (*SignalRunReply, error) {
	out := new(SignalRunReply)
	err := c.cc.Invoke(ctx, RunnerService_SignalRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) TakePendingSignals(ctx context.Context, in *TakePendingSignalsRequest, opts ...grpc.CallOption) (*TakePendingSignalsReply, error) {
	out := new(TakePendingSignalsReply)
	err := c.cc.Invoke(ctx, RunnerService_TakePendingSignals_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) PendingSignalRunIDs(ctx context.Context, in *PendingSignalRunIDsRequest, opts ...grpc.CallOption) (*PendingSignalRunIDsReply, error) {
	out := new(PendingSignalRunIDsReply)
	err := c.cc.Invoke(ctx, RunnerService_PendingSignalRunIDs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) PruneSignals(ctx context.Context, in *PruneSignalsRequest, opts ...grpc.CallOption) (*PruneSignalsReply, error) {
	out := new(PruneSignalsReply)
	err := c.cc.Invoke(ctx, RunnerService_PruneSignals_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) AppendRunActivity(ctx context.Context, in *AppendRunActivityRequest, opts ...grpc.CallOption) (*AppendRunActivityReply, error) {
	out := new(AppendRunActivityReply)
	err := c.cc.Invoke(ctx, RunnerService_AppendRunActivity_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) ListRunActivity(ctx context.Context, in *ListRunActivityRequest, opts ...grpc.CallOption) (*ListRunActivityReply, error) {
	out := new(ListRunActivityReply)
	err := c.cc.Invoke(ctx, RunnerService_ListRunActivity_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) PruneRunActivity(ctx context.Context, in *PruneRunActivityRequest, opts ...grpc.CallOption) (*PruneRunActivityReply, error) {
	out := new(PruneRunActivityReply)
	err := c.cc.Invoke(ctx, RunnerService_PruneRunActivity_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) ReapExpiredRuns(ctx context.Context, in *ReapExpiredRunsRequest, opts ...grpc.CallOption) (*ReapExpiredRunsReply, error) {
	out := new(ReapExpiredRunsReply)
	err := c.cc.Invoke(ctx, RunnerService_ReapExpiredRuns_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnerServiceServer is the server API for RunnerService service.
// All implementations must embed UnimplementedRunnerServiceServer
// for forward compatibility
type RunnerServiceServer interface {
	EnqueueRun(context.Context, *EnqueueRunRequest) (*EnqueueRunReply, error)
	GetRun(context.Context, *GetRunRequest) (*GetRunReply, error)
	GetActiveRunForSession(context.Context, *GetActiveRunForSessionRequest) (*GetRunReply, error)
	ListActiveSessionIDs(context.Context, *ListActiveSessionIDsRequest) (*ListActiveSessionIDsReply, error)
	ClaimRun(context.Context, *ClaimRunRequest) (*ClaimRunReply, error)
	ClaimRunByID(context.Context, *ClaimRunByIDRequest) (*ClaimRunReply, error)
	HeartbeatRun(context.Context, *HeartbeatRunRequest) (*HeartbeatRunReply, error)
	ReleaseRunLease(context.Context, *ReleaseRunLeaseRequest) (*ReleaseRunLeaseReply, error)
	FailRun(context.Context, *FailRunRequest) (*FailRunReply, error)
	AppendRunEvent(context.Context, *AppendRunEventRequest) (*AppendRunEventReply, error)
	CompleteRun(context.Context, *CompleteRunRequest) (*CompleteRunReply, error)
	SignalRun(context.Context, *SignalRunRequest) (*SignalRunReply, error)
	TakePendingSignals(context.Context, *TakePendingSignalsRequest) (*TakePendingSignalsReply, error)
	PendingSignalRunIDs(context.Context, *PendingSignalRunIDsRequest) (*PendingSignalRunIDsReply, error)
	PruneSignals(context.Context, *PruneSignalsRequest) (*PruneSignalsReply, error)
	AppendRunActivity(context.Context, *AppendRunActivityRequest) (*AppendRunActivityReply, error)
	ListRunActivity(context.Context, *ListRunActivityRequest) (*ListRunActivityReply, error)
	PruneRunActivity(context.Context, *PruneRunActivityRequest) (*PruneRunActivityReply, error)
	ReapExpiredRuns(context.Context, *ReapExpiredRunsRequest) (*ReapExpiredRunsReply, error)
	mustEmbedUnimplementedRunnerServiceServer()
}

// UnimplementedRunnerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRunnerServiceServer struct {
}

func (UnimplementedRunnerServiceServer) EnqueueRun(context.Context, *EnqueueRunRequest) (*EnqueueRunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnqueueRun not implemented")
}
func (UnimplementedRunnerServiceServer) GetRun(context.Context, *GetRunRequest) (*GetRunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedRunnerServiceServer) GetActiveRunForSession(context.Context, *GetActiveRunForSessionRequest) (*GetRunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveRunForSession not implemented")
}
func (UnimplementedRunnerServiceServer) ListActiveSessionIDs(context.Context, *ListActiveSessionIDsRequest) (*ListActiveSessionIDsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActiveSessionIDs not implemented")
}
func (UnimplementedRunnerServiceServer) ClaimRun(context.Context, *ClaimRunRequest) (*ClaimRunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimRun not implemented")
}
func (UnimplementedRunnerServiceServer) ClaimRunByID(context.Context, *ClaimRunByIDRequest) (*ClaimRunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimRunByID not implemented")
}
func (UnimplementedRunnerServiceServer) HeartbeatRun(context.Context, *HeartbeatRunRequest) (*HeartbeatRunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartbeatRun not implemented")
}
func (UnimplementedRunnerServiceServer) ReleaseRunLease(context.Context, *ReleaseRunLeaseRequest) (*ReleaseRunLeaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseRunLease not implemented")
}
func (UnimplementedRunnerServiceServer) FailRun(context.Context, *FailRunRequest) (*FailRunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FailRun not implemented")
}
func (UnimplementedRunnerServiceServer) AppendRunEvent(context.Context, *AppendRunEventRequest) (*AppendRunEventReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendRunEvent not implemented")
}
func (UnimplementedRunnerServiceServer) CompleteRun(context.Context, *CompleteRunRequest) (*CompleteRunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteRun not implemented")
}
func (UnimplementedRunnerServiceServer) SignalRun(context.Context, *SignalRunRequest) (*SignalRunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalRun not implemented")
}
func (UnimplementedRunnerServiceServer) TakePendingSignals(context.Context, *TakePendingSignalsRequest) (*TakePendingSignalsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakePendingSignals not implemented")
}
func (UnimplementedRunnerServiceServer) PendingSignalRunIDs(context.Context, *PendingSignalRunIDsRequest) (*PendingSignalRunIDsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingSignalRunIDs not implemented")
}
func (UnimplementedRunnerServiceServer) PruneSignals(context.Context, *PruneSignalsRequest) (*PruneSignalsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PruneSignals not implemented")
}
func (UnimplementedRunnerServiceServer) AppendRunActivity(context.Context, *AppendRunActivityRequest) (*AppendRunActivityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendRunActivity not implemented")
}
func (UnimplementedRunnerServiceServer) ListRunActivity(context.Context, *ListRunActivityRequest) (*ListRunActivityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRunActivity not implemented")
}
func (UnimplementedRunnerServiceServer) PruneRunActivity(context.Context, *PruneRunActivityRequest) (*PruneRunActivityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PruneRunActivity not implemented")
}
func (UnimplementedRunnerServiceServer) ReapExpiredRuns(context.Context, *ReapExpiredRunsRequest) (*ReapExpiredRunsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReapExpiredRuns not implemented")
}
func (UnimplementedRunnerServiceServer) mustEmbedUnimplementedRunnerServiceServer() {}

// UnsafeRunnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerServiceServer will
// result in compilation errors.
type UnsafeRunnerServiceServer interface {
	mustEmbedUnimplementedRunnerServiceServer()
}

func RegisterRunnerServiceServer(s grpc.ServiceRegistrar, srv RunnerServiceServer) {
	s.RegisterService(&RunnerService_ServiceDesc, srv)
}

func _RunnerService_EnqueueRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).EnqueueRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_EnqueueRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).EnqueueRun(ctx, req.(*EnqueueRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).GetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_GetActiveRunForSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveRunForSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).GetActiveRunForSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_GetActiveRunForSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).GetActiveRunForSession(ctx, req.(*GetActiveRunForSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_ListActiveSessionIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveSessionIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).ListActiveSessionIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_ListActiveSessionIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).ListActiveSessionIDs(ctx, req.(*ListActiveSessionIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_ClaimRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).ClaimRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_ClaimRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).ClaimRun(ctx, req.(*ClaimRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_ClaimRunByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimRunByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).ClaimRunByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_ClaimRunByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).ClaimRunByID(ctx, req.(*ClaimRunByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_HeartbeatRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).HeartbeatRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_HeartbeatRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).HeartbeatRun(ctx, req.(*HeartbeatRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_ReleaseRunLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRunLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).ReleaseRunLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_ReleaseRunLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).ReleaseRunLease(ctx, req.(*ReleaseRunLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_FailRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).FailRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_FailRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).FailRun(ctx, req.(*FailRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_AppendRunEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRunEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).AppendRunEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_AppendRunEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).AppendRunEvent(ctx, req.(*AppendRunEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_CompleteRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).CompleteRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_CompleteRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).CompleteRun(ctx, req.(*CompleteRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_SignalRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).SignalRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_SignalRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).SignalRun(ctx, req.(*SignalRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_TakePendingSignals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakePendingSignalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).TakePendingSignals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_TakePendingSignals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).TakePendingSignals(ctx, req.(*TakePendingSignalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_PendingSignalRunIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PendingSignalRunIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).PendingSignalRunIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_PendingSignalRunIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).PendingSignalRunIDs(ctx, req.(*PendingSignalRunIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_PruneSignals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PruneSignalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).PruneSignals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_PruneSignals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).PruneSignals(ctx, req.(*PruneSignalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_AppendRunActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRunActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).AppendRunActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_AppendRunActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).AppendRunActivity(ctx, req.(*AppendRunActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_ListRunActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).ListRunActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_ListRunActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).ListRunActivity(ctx, req.(*ListRunActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_PruneRunActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PruneRunActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).PruneRunActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_PruneRunActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).PruneRunActivity(ctx, req.(*PruneRunActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_ReapExpiredRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReapExpiredRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).ReapExpiredRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_ReapExpiredRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).ReapExpiredRuns(ctx, req.(*ReapExpiredRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunnerService_ServiceDesc is the grpc.ServiceDesc for RunnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qm.runner.v1.RunnerService",
	HandlerType: (*RunnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnqueueRun",
			Handler:    _RunnerService_EnqueueRun_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _RunnerService_GetRun_Handler,
		},
		{
			MethodName: "GetActiveRunForSession",
			Handler:    _RunnerService_GetActiveRunForSession_Handler,
		},
		{
			MethodName: "ListActiveSessionIDs",
			Handler:    _RunnerService_ListActiveSessionIDs_Handler,
		},
		{
			MethodName: "ClaimRun",
			Handler:    _RunnerService_ClaimRun_Handler,
		},
		{
			MethodName: "ClaimRunByID",
			Handler:    _RunnerService_ClaimRunByID_Handler,
		},
		{
			MethodName: "HeartbeatRun",
			Handler:    _RunnerService_HeartbeatRun_Handler,
		},
		{
			MethodName: "ReleaseRunLease",
			Handler:    _RunnerService_ReleaseRunLease_Handler,
		},
		{
			MethodName: "FailRun",
			Handler:    _RunnerService_FailRun_Handler,
		},
		{
			MethodName: "AppendRunEvent",
			Handler:    _RunnerService_AppendRunEvent_Handler,
		},
		{
			MethodName: "CompleteRun",
			Handler:    _RunnerService_CompleteRun_Handler,
		},
		{
			MethodName: "SignalRun",
			Handler:    _RunnerService_SignalRun_Handler,
		},
		{
			MethodName: "TakePendingSignals",
			Handler:    _RunnerService_TakePendingSignals_Handler,
		},
		{
			MethodName: "PendingSignalRunIDs",
			Handler:    _RunnerService_PendingSignalRunIDs_Handler,
		},
		{
			MethodName: "PruneSignals",
			Handler:    _RunnerService_PruneSignals_Handler,
		},
		{
			MethodName: "AppendRunActivity",
			Handler:    _RunnerService_AppendRunActivity_Handler,
		},
		{
			MethodName: "ListRunActivity",
			Handler:    _RunnerService_ListRunActivity_Handler,
		},
		{
			MethodName: "PruneRunActivity",
			Handler:    _RunnerService_PruneRunActivity_Handler,
		},
		{
			MethodName: "ReapExpiredRuns",
			Handler:    _RunnerService_ReapExpiredRuns_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/qm/runner/v1/runner.proto",
}
