package agent

import (
	"context"
	"encoding/json"
	"os"
	"reflect"
	"testing"
)

type conformanceTools struct {
	result ToolResult
	calls  []ToolCall
}

func (t *conformanceTools) Definitions(context.Context, ToolOptions) ([]ToolDefinition, error) {
	return []ToolDefinition{{Name: "knowledge", InputSchema: json.RawMessage(`{"type":"object"}`)}}, nil
}
func (t *conformanceTools) Execute(_ context.Context, c ToolCall) (ToolResult, error) {
	t.calls = append(t.calls, c)
	return t.result, nil
}

// These cases mirror the TS Pi v0.85.1 loop: tool results are messages,
// not a domain-specific instruction to suppress, finish, or reject a turn.
func TestPiLoopTreatsKnowledgeAsOrdinaryTool(t *testing.T) {
	for _, tc := range []struct {
		name, action, payload string
		failed                bool
	}{
		{"read without submit", "read", `{"path":"raw/sources/ch12.txt"}`, false},
		{"incomplete submit", "submit", `{"status":"incomplete","unresolved_requirement_ids":["1"]}`, false},
		{"complete submit", "submit", `{"status":"complete","answer":"tool draft"}`, false},
		{"missing page", "read", `{"code":"knowledge_action_failed"}`, true},
		{"workspace processing", "status", `{"status":"processing"}`, false},
		{"workspace unavailable", "status", `{"code":"knowledge_unavailable"}`, true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			result := toolText(tc.payload)
			result.IsError = tc.failed
			tools := &conformanceTools{result: result}
			transport := &fakePiTransport{completions: []PiCompletion{
				{Text: "checking evidence", ToolCalls: []ToolCall{{ID: "1", Name: "knowledge", Arguments: json.RawMessage(`{"action":"` + tc.action + `"}`)}}},
				{Text: "model final response"},
			}}
			adapter, _ := NewPiAdapter(piTestModels(), transport)
			got, err := adapter.RunTurn(context.Background(), TurnInput{SessionID: "conformance", Input: "question", Model: "model-pi", Tools: tools, Emit: func(_ context.Context, e NewEntry) (SessionEntry, error) { return SessionEntry{Type: e.Type}, nil }})
			if err != nil || got.Reply != "model final response" || len(tools.calls) != 1 || len(transport.requests) != 2 {
				t.Fatalf("result=%+v calls=%d err=%v", got, len(tools.calls), err)
			}
			messages := transport.requests[1].Messages
			if messages[len(messages)-1].Content != tc.payload {
				t.Fatalf("tool result was replaced: %+v", messages)
			}
		})
	}
}

func TestPiLoopExecutesRepeatedCallsAndCallsAfterSubmit(t *testing.T) {
	calls := []ToolCall{}
	for _, id := range []string{"1", "2", "3", "4"} {
		calls = append(calls, ToolCall{ID: id, Name: "knowledge", Arguments: json.RawMessage(`{"action":"submit"}`)})
	}
	tools := &conformanceTools{result: toolText(`{"status":"complete","answer":"draft"}`)}
	transport := &fakePiTransport{completions: []PiCompletion{{ToolCalls: calls}, {Text: "final"}}}
	adapter, _ := NewPiAdapter(piTestModels(), transport)
	got, err := adapter.RunTurn(context.Background(), TurnInput{SessionID: "conformance", Input: "q", Model: "model-pi", Tools: tools, Emit: func(_ context.Context, e NewEntry) (SessionEntry, error) { return SessionEntry{Type: e.Type}, nil }})
	if err != nil || got.Reply != "final" || len(tools.calls) != 4 {
		t.Fatalf("result=%+v calls=%d err=%v", got, len(tools.calls), err)
	}
}

func TestPiLoopNeverExecutesTruncatedToolCalls(t *testing.T) {
	tools := &conformanceTools{result: toolText("ok")}
	transport := &fakePiTransport{completions: []PiCompletion{{StopReason: "length", ToolCalls: []ToolCall{{ID: "1", Name: "knowledge", Arguments: json.RawMessage(`{"action":"read"}`)}}}, {Text: "retry explanation"}}}
	adapter, _ := NewPiAdapter(piTestModels(), transport)
	got, err := adapter.RunTurn(context.Background(), TurnInput{SessionID: "conformance", Input: "q", Model: "model-pi", Tools: tools, Emit: func(_ context.Context, e NewEntry) (SessionEntry, error) { return SessionEntry{Type: e.Type}, nil }})
	if err != nil || len(tools.calls) != 0 || got.Reply != "retry explanation" {
		t.Fatalf("result=%+v calls=%d err=%v", got, len(tools.calls), err)
	}
}

// Generated by the actual pinned upstream runtime, not by the Go implementation.
func TestPiLoopMatchesTypeScriptReference(t *testing.T) {
	var cases []struct {
		Name        string
		Payload     string
		Failed      bool
		Completions []struct {
			Text, StopReason string
			Calls            []struct{ ID, Action string }
		}
	}
	raw, err := os.ReadFile("testdata/pi-loop-cases.json")
	if err != nil {
		t.Fatal(err)
	}
	if err = json.Unmarshal(raw, &cases); err != nil {
		t.Fatal(err)
	}
	var reference struct {
		Cases []struct {
			Name       string
			ModelCalls int
			Executed   []string
			Reply      string
		}
	}
	raw, err = os.ReadFile("testdata/pi-loop-reference.json")
	if err != nil {
		t.Fatal(err)
	}
	if err = json.Unmarshal(raw, &reference); err != nil {
		t.Fatal(err)
	}
	for i, c := range cases {
		t.Run(c.Name, func(t *testing.T) {
			frames := []PiCompletion{}
			for _, frame := range c.Completions {
				pc := PiCompletion{Text: frame.Text, StopReason: frame.StopReason}
				for _, call := range frame.Calls {
					pc.ToolCalls = append(pc.ToolCalls, ToolCall{ID: call.ID, Name: "knowledge", Arguments: json.RawMessage(`{"action":"` + call.Action + `"}`)})
				}
				frames = append(frames, pc)
			}
			tools := &conformanceTools{result: toolText(c.Payload)}
			tools.result.IsError = c.Failed
			transport := &fakePiTransport{completions: frames}
			adapter, _ := NewPiAdapter(piTestModels(), transport)
			got, err := adapter.RunTurn(t.Context(), TurnInput{SessionID: "reference", Input: "question", Model: "model-pi", Tools: tools, Emit: func(_ context.Context, e NewEntry) (SessionEntry, error) { return SessionEntry{Type: e.Type}, nil }})
			expected := reference.Cases[i]
			ids := []string{}
			for _, call := range tools.calls {
				ids = append(ids, call.ID)
			}
			if err != nil || got.Reply != expected.Reply || got.ModelCalls != expected.ModelCalls || !reflect.DeepEqual(ids, expected.Executed) {
				t.Fatalf("Go result=%+v executed=%v TS=%+v err=%v", got, ids, expected, err)
			}
		})
	}
}
